// Generated by dia2code
#ifndef SERVER__USERDB__H
#define SERVER__USERDB__H

#include <map>
#include <memory>

namespace server {
  class User;
}

#include "User.h"

namespace server {

  /// class UserDB - 
  class UserDB {
    // Associations
    // Attributes
  protected:
    int idseq;
    std::map<int,std::unique_ptr<User> > users;
    // Operations
  public:
    UserDB ();
    User* getUser (int id) const;
    int addUser ();
    void removeUser (int id);
  };

};

#endif
