// Generated by dia2code
#ifndef SERVER__USER__H
#define SERVER__USER__H


namespace server {

  /// class User - 
  class User {
    // Attributes
  public:
    bool take_command_from[2];
    bool ai;
  };

};

#endif
