<<<<<<< HEAD
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/corentin/Documents/tank

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/corentin/Documents/tank

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/corentin/Documents/tank/CMakeFiles /home/corentin/Documents/tank/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/corentin/Documents/tank/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/state/Element.o: src/state/Element.cpp.o

.PHONY : src/state/Element.o

# target to build an object file
src/state/Element.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Element.cpp.o
.PHONY : src/state/Element.cpp.o

src/state/Element.i: src/state/Element.cpp.i

.PHONY : src/state/Element.i

# target to preprocess a source file
src/state/Element.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Element.cpp.i
.PHONY : src/state/Element.cpp.i

src/state/Element.s: src/state/Element.cpp.s

.PHONY : src/state/Element.s

# target to generate assembly for a file
src/state/Element.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Element.cpp.s
.PHONY : src/state/Element.cpp.s

src/state/ElementGrid.o: src/state/ElementGrid.cpp.o

.PHONY : src/state/ElementGrid.o

# target to build an object file
src/state/ElementGrid.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementGrid.cpp.o
.PHONY : src/state/ElementGrid.cpp.o

src/state/ElementGrid.i: src/state/ElementGrid.cpp.i

.PHONY : src/state/ElementGrid.i

# target to preprocess a source file
src/state/ElementGrid.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementGrid.cpp.i
.PHONY : src/state/ElementGrid.cpp.i

src/state/ElementGrid.s: src/state/ElementGrid.cpp.s

.PHONY : src/state/ElementGrid.s

# target to generate assembly for a file
src/state/ElementGrid.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementGrid.cpp.s
.PHONY : src/state/ElementGrid.cpp.s

src/state/ElementList.o: src/state/ElementList.cpp.o

.PHONY : src/state/ElementList.o

# target to build an object file
src/state/ElementList.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementList.cpp.o
.PHONY : src/state/ElementList.cpp.o

src/state/ElementList.i: src/state/ElementList.cpp.i

.PHONY : src/state/ElementList.i

# target to preprocess a source file
src/state/ElementList.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementList.cpp.i
.PHONY : src/state/ElementList.cpp.i

src/state/ElementList.s: src/state/ElementList.cpp.s

.PHONY : src/state/ElementList.s

# target to generate assembly for a file
src/state/ElementList.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementList.cpp.s
.PHONY : src/state/ElementList.cpp.s

src/state/Missile.o: src/state/Missile.cpp.o

.PHONY : src/state/Missile.o

# target to build an object file
src/state/Missile.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Missile.cpp.o
.PHONY : src/state/Missile.cpp.o

src/state/Missile.i: src/state/Missile.cpp.i

.PHONY : src/state/Missile.i

# target to preprocess a source file
src/state/Missile.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Missile.cpp.i
.PHONY : src/state/Missile.cpp.i

src/state/Missile.s: src/state/Missile.cpp.s

.PHONY : src/state/Missile.s

# target to generate assembly for a file
src/state/Missile.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Missile.cpp.s
.PHONY : src/state/Missile.cpp.s

src/state/Mobile.o: src/state/Mobile.cpp.o

.PHONY : src/state/Mobile.o

# target to build an object file
src/state/Mobile.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Mobile.cpp.o
.PHONY : src/state/Mobile.cpp.o

src/state/Mobile.i: src/state/Mobile.cpp.i

.PHONY : src/state/Mobile.i

# target to preprocess a source file
src/state/Mobile.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Mobile.cpp.i
.PHONY : src/state/Mobile.cpp.i

src/state/Mobile.s: src/state/Mobile.cpp.s

.PHONY : src/state/Mobile.s

# target to generate assembly for a file
src/state/Mobile.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Mobile.cpp.s
.PHONY : src/state/Mobile.cpp.s

src/state/Obstacle.o: src/state/Obstacle.cpp.o

.PHONY : src/state/Obstacle.o

# target to build an object file
src/state/Obstacle.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Obstacle.cpp.o
.PHONY : src/state/Obstacle.cpp.o

src/state/Obstacle.i: src/state/Obstacle.cpp.i

.PHONY : src/state/Obstacle.i

# target to preprocess a source file
src/state/Obstacle.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Obstacle.cpp.i
.PHONY : src/state/Obstacle.cpp.i

src/state/Obstacle.s: src/state/Obstacle.cpp.s

.PHONY : src/state/Obstacle.s

# target to generate assembly for a file
src/state/Obstacle.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Obstacle.cpp.s
.PHONY : src/state/Obstacle.cpp.s

src/state/Projectile.o: src/state/Projectile.cpp.o

.PHONY : src/state/Projectile.o

# target to build an object file
src/state/Projectile.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Projectile.cpp.o
.PHONY : src/state/Projectile.cpp.o

src/state/Projectile.i: src/state/Projectile.cpp.i

.PHONY : src/state/Projectile.i

# target to preprocess a source file
src/state/Projectile.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Projectile.cpp.i
.PHONY : src/state/Projectile.cpp.i

src/state/Projectile.s: src/state/Projectile.cpp.s

.PHONY : src/state/Projectile.s

# target to generate assembly for a file
src/state/Projectile.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Projectile.cpp.s
.PHONY : src/state/Projectile.cpp.s

src/state/Shell.o: src/state/Shell.cpp.o

.PHONY : src/state/Shell.o

# target to build an object file
src/state/Shell.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Shell.cpp.o
.PHONY : src/state/Shell.cpp.o

src/state/Shell.i: src/state/Shell.cpp.i

.PHONY : src/state/Shell.i

# target to preprocess a source file
src/state/Shell.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Shell.cpp.i
.PHONY : src/state/Shell.cpp.i

src/state/Shell.s: src/state/Shell.cpp.s

.PHONY : src/state/Shell.s

# target to generate assembly for a file
src/state/Shell.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Shell.cpp.s
.PHONY : src/state/Shell.cpp.s

src/state/Space.o: src/state/Space.cpp.o

.PHONY : src/state/Space.o

# target to build an object file
src/state/Space.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Space.cpp.o
.PHONY : src/state/Space.cpp.o

src/state/Space.i: src/state/Space.cpp.i

.PHONY : src/state/Space.i

# target to preprocess a source file
src/state/Space.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Space.cpp.i
.PHONY : src/state/Space.cpp.i

src/state/Space.s: src/state/Space.cpp.s

.PHONY : src/state/Space.s

# target to generate assembly for a file
src/state/Space.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Space.cpp.s
.PHONY : src/state/Space.cpp.s

src/state/State.o: src/state/State.cpp.o

.PHONY : src/state/State.o

# target to build an object file
src/state/State.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/State.cpp.o
.PHONY : src/state/State.cpp.o

src/state/State.i: src/state/State.cpp.i

.PHONY : src/state/State.i

# target to preprocess a source file
src/state/State.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/State.cpp.i
.PHONY : src/state/State.cpp.i

src/state/State.s: src/state/State.cpp.s

.PHONY : src/state/State.s

# target to generate assembly for a file
src/state/State.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/State.cpp.s
.PHONY : src/state/State.cpp.s

src/state/StaticElement.o: src/state/StaticElement.cpp.o

.PHONY : src/state/StaticElement.o

# target to build an object file
src/state/StaticElement.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/StaticElement.cpp.o
.PHONY : src/state/StaticElement.cpp.o

src/state/StaticElement.i: src/state/StaticElement.cpp.i

.PHONY : src/state/StaticElement.i

# target to preprocess a source file
src/state/StaticElement.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/StaticElement.cpp.i
.PHONY : src/state/StaticElement.cpp.i

src/state/StaticElement.s: src/state/StaticElement.cpp.s

.PHONY : src/state/StaticElement.s

# target to generate assembly for a file
src/state/StaticElement.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/StaticElement.cpp.s
.PHONY : src/state/StaticElement.cpp.s

src/state/Tank.o: src/state/Tank.cpp.o

.PHONY : src/state/Tank.o

# target to build an object file
src/state/Tank.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Tank.cpp.o
.PHONY : src/state/Tank.cpp.o

src/state/Tank.i: src/state/Tank.cpp.i

.PHONY : src/state/Tank.i

# target to preprocess a source file
src/state/Tank.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Tank.cpp.i
.PHONY : src/state/Tank.cpp.i

src/state/Tank.s: src/state/Tank.cpp.s

.PHONY : src/state/Tank.s

# target to generate assembly for a file
src/state/Tank.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Tank.cpp.s
.PHONY : src/state/Tank.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/state/Element.o"
	@echo "... src/state/Element.i"
	@echo "... src/state/Element.s"
	@echo "... src/state/ElementGrid.o"
	@echo "... src/state/ElementGrid.i"
	@echo "... src/state/ElementGrid.s"
	@echo "... src/state/ElementList.o"
	@echo "... src/state/ElementList.i"
	@echo "... src/state/ElementList.s"
	@echo "... src/state/Missile.o"
	@echo "... src/state/Missile.i"
	@echo "... src/state/Missile.s"
	@echo "... src/state/Mobile.o"
	@echo "... src/state/Mobile.i"
	@echo "... src/state/Mobile.s"
	@echo "... src/state/Obstacle.o"
	@echo "... src/state/Obstacle.i"
	@echo "... src/state/Obstacle.s"
	@echo "... src/state/Projectile.o"
	@echo "... src/state/Projectile.i"
	@echo "... src/state/Projectile.s"
	@echo "... src/state/Shell.o"
	@echo "... src/state/Shell.i"
	@echo "... src/state/Shell.s"
	@echo "... src/state/Space.o"
	@echo "... src/state/Space.i"
	@echo "... src/state/Space.s"
	@echo "... src/state/State.o"
	@echo "... src/state/State.i"
	@echo "... src/state/State.s"
	@echo "... src/state/StaticElement.o"
	@echo "... src/state/StaticElement.i"
	@echo "... src/state/StaticElement.s"
	@echo "... src/state/Tank.o"
	@echo "... src/state/Tank.i"
	@echo "... src/state/Tank.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

=======


HEADERS:=$(shell find src -type f -name '*.h')
DIA2CODE_DIR:=./dia2code

all: | clean dia2code configure build

clean:
	@rm -rf bin build ${HEADERS}
	@rm -f $(shell grep -ls '// Generated by dia2code' main.h ${HEADERS})

distclean: clean
	@rm -rf ${DIA2CODE_DIR}/bin ${DIA2CODE_DIR}/build

dia2code: ${DIA2CODE_DIR}/bin/dia2code

${DIA2CODE_DIR}/bin/dia2code: 
	cd ${DIA2CODE_DIR} && ./build.sh

configure:
	@mkdir -p build 
	@cd build && cmake ..

build:
	@make -s -j4 -C build

run: build
	./bin/run

test:
	docker build -t plt-initial -f docker/plt-initial .
	docker build -t plt-build -f docker/plt-build .
	./docker/run_docker_x11.sh plt-build

start-kit: distclean
	@tar -czvf ../plt-start-kit.tar.gz CMakeLists.txt Makefile .gitignore dia2code src docker rapport res

.PHONY: configure build clean run test start-kit
>>>>>>> parent of 7163334... Merge branch 'newbranch'
