# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/morisse/Documents/tank

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/morisse/Documents/tank

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/morisse/Documents/tank/CMakeFiles /home/morisse/Documents/tank/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/morisse/Documents/tank/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

extern/jsoncpp-0.10.5/dist/jsoncpp.o: extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.o

.PHONY : extern/jsoncpp-0.10.5/dist/jsoncpp.o

# target to build an object file
extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.o
.PHONY : extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.o

extern/jsoncpp-0.10.5/dist/jsoncpp.i: extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.i

.PHONY : extern/jsoncpp-0.10.5/dist/jsoncpp.i

# target to preprocess a source file
extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.i
.PHONY : extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.i

extern/jsoncpp-0.10.5/dist/jsoncpp.s: extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.s

.PHONY : extern/jsoncpp-0.10.5/dist/jsoncpp.s

# target to generate assembly for a file
extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.s
.PHONY : extern/jsoncpp-0.10.5/dist/jsoncpp.cpp.s

src/ai/AI.o: src/ai/AI.cpp.o

.PHONY : src/ai/AI.o

# target to build an object file
src/ai/AI.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/AI.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/AI.cpp.o
.PHONY : src/ai/AI.cpp.o

src/ai/AI.i: src/ai/AI.cpp.i

.PHONY : src/ai/AI.i

# target to preprocess a source file
src/ai/AI.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/AI.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/AI.cpp.i
.PHONY : src/ai/AI.cpp.i

src/ai/AI.s: src/ai/AI.cpp.s

.PHONY : src/ai/AI.s

# target to generate assembly for a file
src/ai/AI.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/AI.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/AI.cpp.s
.PHONY : src/ai/AI.cpp.s

src/ai/DistanceUtility.o: src/ai/DistanceUtility.cpp.o

.PHONY : src/ai/DistanceUtility.o

# target to build an object file
src/ai/DistanceUtility.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/DistanceUtility.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/DistanceUtility.cpp.o
.PHONY : src/ai/DistanceUtility.cpp.o

src/ai/DistanceUtility.i: src/ai/DistanceUtility.cpp.i

.PHONY : src/ai/DistanceUtility.i

# target to preprocess a source file
src/ai/DistanceUtility.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/DistanceUtility.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/DistanceUtility.cpp.i
.PHONY : src/ai/DistanceUtility.cpp.i

src/ai/DistanceUtility.s: src/ai/DistanceUtility.cpp.s

.PHONY : src/ai/DistanceUtility.s

# target to generate assembly for a file
src/ai/DistanceUtility.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/DistanceUtility.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/DistanceUtility.cpp.s
.PHONY : src/ai/DistanceUtility.cpp.s

src/ai/DumbAI.o: src/ai/DumbAI.cpp.o

.PHONY : src/ai/DumbAI.o

# target to build an object file
src/ai/DumbAI.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/DumbAI.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/DumbAI.cpp.o
.PHONY : src/ai/DumbAI.cpp.o

src/ai/DumbAI.i: src/ai/DumbAI.cpp.i

.PHONY : src/ai/DumbAI.i

# target to preprocess a source file
src/ai/DumbAI.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/DumbAI.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/DumbAI.cpp.i
.PHONY : src/ai/DumbAI.cpp.i

src/ai/DumbAI.s: src/ai/DumbAI.cpp.s

.PHONY : src/ai/DumbAI.s

# target to generate assembly for a file
src/ai/DumbAI.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/DumbAI.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/DumbAI.cpp.s
.PHONY : src/ai/DumbAI.cpp.s

src/ai/EvolvedAI.o: src/ai/EvolvedAI.cpp.o

.PHONY : src/ai/EvolvedAI.o

# target to build an object file
src/ai/EvolvedAI.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/EvolvedAI.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/EvolvedAI.cpp.o
.PHONY : src/ai/EvolvedAI.cpp.o

src/ai/EvolvedAI.i: src/ai/EvolvedAI.cpp.i

.PHONY : src/ai/EvolvedAI.i

# target to preprocess a source file
src/ai/EvolvedAI.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/EvolvedAI.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/EvolvedAI.cpp.i
.PHONY : src/ai/EvolvedAI.cpp.i

src/ai/EvolvedAI.s: src/ai/EvolvedAI.cpp.s

.PHONY : src/ai/EvolvedAI.s

# target to generate assembly for a file
src/ai/EvolvedAI.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/EvolvedAI.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/EvolvedAI.cpp.s
.PHONY : src/ai/EvolvedAI.cpp.s

src/ai/Gardener.o: src/ai/Gardener.cpp.o

.PHONY : src/ai/Gardener.o

# target to build an object file
src/ai/Gardener.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/Gardener.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/Gardener.cpp.o
.PHONY : src/ai/Gardener.cpp.o

src/ai/Gardener.i: src/ai/Gardener.cpp.i

.PHONY : src/ai/Gardener.i

# target to preprocess a source file
src/ai/Gardener.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/Gardener.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/Gardener.cpp.i
.PHONY : src/ai/Gardener.cpp.i

src/ai/Gardener.s: src/ai/Gardener.cpp.s

.PHONY : src/ai/Gardener.s

# target to generate assembly for a file
src/ai/Gardener.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/Gardener.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/Gardener.cpp.s
.PHONY : src/ai/Gardener.cpp.s

src/ai/HeuristicAI.o: src/ai/HeuristicAI.cpp.o

.PHONY : src/ai/HeuristicAI.o

# target to build an object file
src/ai/HeuristicAI.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/HeuristicAI.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/HeuristicAI.cpp.o
.PHONY : src/ai/HeuristicAI.cpp.o

src/ai/HeuristicAI.i: src/ai/HeuristicAI.cpp.i

.PHONY : src/ai/HeuristicAI.i

# target to preprocess a source file
src/ai/HeuristicAI.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/HeuristicAI.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/HeuristicAI.cpp.i
.PHONY : src/ai/HeuristicAI.cpp.i

src/ai/HeuristicAI.s: src/ai/HeuristicAI.cpp.s

.PHONY : src/ai/HeuristicAI.s

# target to generate assembly for a file
src/ai/HeuristicAI.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/HeuristicAI.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/HeuristicAI.cpp.s
.PHONY : src/ai/HeuristicAI.cpp.s

src/ai/TreeAI.o: src/ai/TreeAI.cpp.o

.PHONY : src/ai/TreeAI.o

# target to build an object file
src/ai/TreeAI.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/TreeAI.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/TreeAI.cpp.o
.PHONY : src/ai/TreeAI.cpp.o

src/ai/TreeAI.i: src/ai/TreeAI.cpp.i

.PHONY : src/ai/TreeAI.i

# target to preprocess a source file
src/ai/TreeAI.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/TreeAI.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/TreeAI.cpp.i
.PHONY : src/ai/TreeAI.cpp.i

src/ai/TreeAI.s: src/ai/TreeAI.cpp.s

.PHONY : src/ai/TreeAI.s

# target to generate assembly for a file
src/ai/TreeAI.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ai/TreeAI.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ai/TreeAI.cpp.s
.PHONY : src/ai/TreeAI.cpp.s

src/client/Button.o: src/client/Button.cpp.o

.PHONY : src/client/Button.o

# target to build an object file
src/client/Button.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/Button.cpp.o
.PHONY : src/client/Button.cpp.o

src/client/Button.i: src/client/Button.cpp.i

.PHONY : src/client/Button.i

# target to preprocess a source file
src/client/Button.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/Button.cpp.i
.PHONY : src/client/Button.cpp.i

src/client/Button.s: src/client/Button.cpp.s

.PHONY : src/client/Button.s

# target to generate assembly for a file
src/client/Button.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/Button.cpp.s
.PHONY : src/client/Button.cpp.s

src/client/CacheStateObserver.o: src/client/CacheStateObserver.cpp.o

.PHONY : src/client/CacheStateObserver.o

# target to build an object file
src/client/CacheStateObserver.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/CacheStateObserver.cpp.o
.PHONY : src/client/CacheStateObserver.cpp.o

src/client/CacheStateObserver.i: src/client/CacheStateObserver.cpp.i

.PHONY : src/client/CacheStateObserver.i

# target to preprocess a source file
src/client/CacheStateObserver.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/CacheStateObserver.cpp.i
.PHONY : src/client/CacheStateObserver.cpp.i

src/client/CacheStateObserver.s: src/client/CacheStateObserver.cpp.s

.PHONY : src/client/CacheStateObserver.s

# target to generate assembly for a file
src/client/CacheStateObserver.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/CacheStateObserver.cpp.s
.PHONY : src/client/CacheStateObserver.cpp.s

src/client/Pilote.o: src/client/Pilote.cpp.o

.PHONY : src/client/Pilote.o

# target to build an object file
src/client/Pilote.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/Pilote.cpp.o
.PHONY : src/client/Pilote.cpp.o

src/client/Pilote.i: src/client/Pilote.cpp.i

.PHONY : src/client/Pilote.i

# target to preprocess a source file
src/client/Pilote.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/Pilote.cpp.i
.PHONY : src/client/Pilote.cpp.i

src/client/Pilote.s: src/client/Pilote.cpp.s

.PHONY : src/client/Pilote.s

# target to generate assembly for a file
src/client/Pilote.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/Pilote.cpp.s
.PHONY : src/client/Pilote.cpp.s

src/client/PiloteSFML.o: src/client/PiloteSFML.cpp.o

.PHONY : src/client/PiloteSFML.o

# target to build an object file
src/client/PiloteSFML.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/PiloteSFML.cpp.o
.PHONY : src/client/PiloteSFML.cpp.o

src/client/PiloteSFML.i: src/client/PiloteSFML.cpp.i

.PHONY : src/client/PiloteSFML.i

# target to preprocess a source file
src/client/PiloteSFML.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/PiloteSFML.cpp.i
.PHONY : src/client/PiloteSFML.cpp.i

src/client/PiloteSFML.s: src/client/PiloteSFML.cpp.s

.PHONY : src/client/PiloteSFML.s

# target to generate assembly for a file
src/client/PiloteSFML.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/PiloteSFML.cpp.s
.PHONY : src/client/PiloteSFML.cpp.s

src/client/main.o: src/client/main.cpp.o

.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i

.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s

.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/engine/Action.o: src/engine/Action.cpp.o

.PHONY : src/engine/Action.o

# target to build an object file
src/engine/Action.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Action.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Action.cpp.o
.PHONY : src/engine/Action.cpp.o

src/engine/Action.i: src/engine/Action.cpp.i

.PHONY : src/engine/Action.i

# target to preprocess a source file
src/engine/Action.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Action.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Action.cpp.i
.PHONY : src/engine/Action.cpp.i

src/engine/Action.s: src/engine/Action.cpp.s

.PHONY : src/engine/Action.s

# target to generate assembly for a file
src/engine/Action.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Action.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Action.cpp.s
.PHONY : src/engine/Action.cpp.s

src/engine/ActionDirection.o: src/engine/ActionDirection.cpp.o

.PHONY : src/engine/ActionDirection.o

# target to build an object file
src/engine/ActionDirection.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ActionDirection.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ActionDirection.cpp.o
.PHONY : src/engine/ActionDirection.cpp.o

src/engine/ActionDirection.i: src/engine/ActionDirection.cpp.i

.PHONY : src/engine/ActionDirection.i

# target to preprocess a source file
src/engine/ActionDirection.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ActionDirection.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ActionDirection.cpp.i
.PHONY : src/engine/ActionDirection.cpp.i

src/engine/ActionDirection.s: src/engine/ActionDirection.cpp.s

.PHONY : src/engine/ActionDirection.s

# target to generate assembly for a file
src/engine/ActionDirection.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ActionDirection.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ActionDirection.cpp.s
.PHONY : src/engine/ActionDirection.cpp.s

src/engine/ActionListTurn.o: src/engine/ActionListTurn.cpp.o

.PHONY : src/engine/ActionListTurn.o

# target to build an object file
src/engine/ActionListTurn.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ActionListTurn.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ActionListTurn.cpp.o
.PHONY : src/engine/ActionListTurn.cpp.o

src/engine/ActionListTurn.i: src/engine/ActionListTurn.cpp.i

.PHONY : src/engine/ActionListTurn.i

# target to preprocess a source file
src/engine/ActionListTurn.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ActionListTurn.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ActionListTurn.cpp.i
.PHONY : src/engine/ActionListTurn.cpp.i

src/engine/ActionListTurn.s: src/engine/ActionListTurn.cpp.s

.PHONY : src/engine/ActionListTurn.s

# target to generate assembly for a file
src/engine/ActionListTurn.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ActionListTurn.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ActionListTurn.cpp.s
.PHONY : src/engine/ActionListTurn.cpp.s

src/engine/ActionMove.o: src/engine/ActionMove.cpp.o

.PHONY : src/engine/ActionMove.o

# target to build an object file
src/engine/ActionMove.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ActionMove.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ActionMove.cpp.o
.PHONY : src/engine/ActionMove.cpp.o

src/engine/ActionMove.i: src/engine/ActionMove.cpp.i

.PHONY : src/engine/ActionMove.i

# target to preprocess a source file
src/engine/ActionMove.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ActionMove.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ActionMove.cpp.i
.PHONY : src/engine/ActionMove.cpp.i

src/engine/ActionMove.s: src/engine/ActionMove.cpp.s

.PHONY : src/engine/ActionMove.s

# target to generate assembly for a file
src/engine/ActionMove.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ActionMove.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ActionMove.cpp.s
.PHONY : src/engine/ActionMove.cpp.s

src/engine/ActionShot.o: src/engine/ActionShot.cpp.o

.PHONY : src/engine/ActionShot.o

# target to build an object file
src/engine/ActionShot.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ActionShot.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ActionShot.cpp.o
.PHONY : src/engine/ActionShot.cpp.o

src/engine/ActionShot.i: src/engine/ActionShot.cpp.i

.PHONY : src/engine/ActionShot.i

# target to preprocess a source file
src/engine/ActionShot.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ActionShot.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ActionShot.cpp.i
.PHONY : src/engine/ActionShot.cpp.i

src/engine/ActionShot.s: src/engine/ActionShot.cpp.s

.PHONY : src/engine/ActionShot.s

# target to generate assembly for a file
src/engine/ActionShot.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ActionShot.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ActionShot.cpp.s
.PHONY : src/engine/ActionShot.cpp.s

src/engine/Command.o: src/engine/Command.cpp.o

.PHONY : src/engine/Command.o

# target to build an object file
src/engine/Command.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Command.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Command.cpp.o
.PHONY : src/engine/Command.cpp.o

src/engine/Command.i: src/engine/Command.cpp.i

.PHONY : src/engine/Command.i

# target to preprocess a source file
src/engine/Command.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Command.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Command.cpp.i
.PHONY : src/engine/Command.cpp.i

src/engine/Command.s: src/engine/Command.cpp.s

.PHONY : src/engine/Command.s

# target to generate assembly for a file
src/engine/Command.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Command.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Command.cpp.s
.PHONY : src/engine/Command.cpp.s

src/engine/CommandSet.o: src/engine/CommandSet.cpp.o

.PHONY : src/engine/CommandSet.o

# target to build an object file
src/engine/CommandSet.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/CommandSet.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/CommandSet.cpp.o
.PHONY : src/engine/CommandSet.cpp.o

src/engine/CommandSet.i: src/engine/CommandSet.cpp.i

.PHONY : src/engine/CommandSet.i

# target to preprocess a source file
src/engine/CommandSet.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/CommandSet.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/CommandSet.cpp.i
.PHONY : src/engine/CommandSet.cpp.i

src/engine/CommandSet.s: src/engine/CommandSet.cpp.s

.PHONY : src/engine/CommandSet.s

# target to generate assembly for a file
src/engine/CommandSet.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/CommandSet.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/CommandSet.cpp.s
.PHONY : src/engine/CommandSet.cpp.s

src/engine/DirectionCommand.o: src/engine/DirectionCommand.cpp.o

.PHONY : src/engine/DirectionCommand.o

# target to build an object file
src/engine/DirectionCommand.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/DirectionCommand.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/DirectionCommand.cpp.o
.PHONY : src/engine/DirectionCommand.cpp.o

src/engine/DirectionCommand.i: src/engine/DirectionCommand.cpp.i

.PHONY : src/engine/DirectionCommand.i

# target to preprocess a source file
src/engine/DirectionCommand.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/DirectionCommand.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/DirectionCommand.cpp.i
.PHONY : src/engine/DirectionCommand.cpp.i

src/engine/DirectionCommand.s: src/engine/DirectionCommand.cpp.s

.PHONY : src/engine/DirectionCommand.s

# target to generate assembly for a file
src/engine/DirectionCommand.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/DirectionCommand.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/DirectionCommand.cpp.s
.PHONY : src/engine/DirectionCommand.cpp.s

src/engine/EndTurnCommand.o: src/engine/EndTurnCommand.cpp.o

.PHONY : src/engine/EndTurnCommand.o

# target to build an object file
src/engine/EndTurnCommand.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/EndTurnCommand.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/EndTurnCommand.cpp.o
.PHONY : src/engine/EndTurnCommand.cpp.o

src/engine/EndTurnCommand.i: src/engine/EndTurnCommand.cpp.i

.PHONY : src/engine/EndTurnCommand.i

# target to preprocess a source file
src/engine/EndTurnCommand.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/EndTurnCommand.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/EndTurnCommand.cpp.i
.PHONY : src/engine/EndTurnCommand.cpp.i

src/engine/EndTurnCommand.s: src/engine/EndTurnCommand.cpp.s

.PHONY : src/engine/EndTurnCommand.s

# target to generate assembly for a file
src/engine/EndTurnCommand.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/EndTurnCommand.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/EndTurnCommand.cpp.s
.PHONY : src/engine/EndTurnCommand.cpp.s

src/engine/Engine.o: src/engine/Engine.cpp.o

.PHONY : src/engine/Engine.o

# target to build an object file
src/engine/Engine.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Engine.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Engine.cpp.o
.PHONY : src/engine/Engine.cpp.o

src/engine/Engine.i: src/engine/Engine.cpp.i

.PHONY : src/engine/Engine.i

# target to preprocess a source file
src/engine/Engine.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Engine.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Engine.cpp.i
.PHONY : src/engine/Engine.cpp.i

src/engine/Engine.s: src/engine/Engine.cpp.s

.PHONY : src/engine/Engine.s

# target to generate assembly for a file
src/engine/Engine.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Engine.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Engine.cpp.s
.PHONY : src/engine/Engine.cpp.s

src/engine/LoadCommand.o: src/engine/LoadCommand.cpp.o

.PHONY : src/engine/LoadCommand.o

# target to build an object file
src/engine/LoadCommand.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/LoadCommand.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/LoadCommand.cpp.o
.PHONY : src/engine/LoadCommand.cpp.o

src/engine/LoadCommand.i: src/engine/LoadCommand.cpp.i

.PHONY : src/engine/LoadCommand.i

# target to preprocess a source file
src/engine/LoadCommand.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/LoadCommand.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/LoadCommand.cpp.i
.PHONY : src/engine/LoadCommand.cpp.i

src/engine/LoadCommand.s: src/engine/LoadCommand.cpp.s

.PHONY : src/engine/LoadCommand.s

# target to generate assembly for a file
src/engine/LoadCommand.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/LoadCommand.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/LoadCommand.cpp.s
.PHONY : src/engine/LoadCommand.cpp.s

src/engine/ModeCommand.o: src/engine/ModeCommand.cpp.o

.PHONY : src/engine/ModeCommand.o

# target to build an object file
src/engine/ModeCommand.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ModeCommand.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ModeCommand.cpp.o
.PHONY : src/engine/ModeCommand.cpp.o

src/engine/ModeCommand.i: src/engine/ModeCommand.cpp.i

.PHONY : src/engine/ModeCommand.i

# target to preprocess a source file
src/engine/ModeCommand.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ModeCommand.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ModeCommand.cpp.i
.PHONY : src/engine/ModeCommand.cpp.i

src/engine/ModeCommand.s: src/engine/ModeCommand.cpp.s

.PHONY : src/engine/ModeCommand.s

# target to generate assembly for a file
src/engine/ModeCommand.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ModeCommand.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ModeCommand.cpp.s
.PHONY : src/engine/ModeCommand.cpp.s

src/engine/MoveCommand.o: src/engine/MoveCommand.cpp.o

.PHONY : src/engine/MoveCommand.o

# target to build an object file
src/engine/MoveCommand.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/MoveCommand.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/MoveCommand.cpp.o
.PHONY : src/engine/MoveCommand.cpp.o

src/engine/MoveCommand.i: src/engine/MoveCommand.cpp.i

.PHONY : src/engine/MoveCommand.i

# target to preprocess a source file
src/engine/MoveCommand.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/MoveCommand.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/MoveCommand.cpp.i
.PHONY : src/engine/MoveCommand.cpp.i

src/engine/MoveCommand.s: src/engine/MoveCommand.cpp.s

.PHONY : src/engine/MoveCommand.s

# target to generate assembly for a file
src/engine/MoveCommand.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/MoveCommand.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/MoveCommand.cpp.s
.PHONY : src/engine/MoveCommand.cpp.s

src/engine/Record.o: src/engine/Record.cpp.o

.PHONY : src/engine/Record.o

# target to build an object file
src/engine/Record.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Record.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Record.cpp.o
.PHONY : src/engine/Record.cpp.o

src/engine/Record.i: src/engine/Record.cpp.i

.PHONY : src/engine/Record.i

# target to preprocess a source file
src/engine/Record.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Record.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Record.cpp.i
.PHONY : src/engine/Record.cpp.i

src/engine/Record.s: src/engine/Record.cpp.s

.PHONY : src/engine/Record.s

# target to generate assembly for a file
src/engine/Record.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Record.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Record.cpp.s
.PHONY : src/engine/Record.cpp.s

src/engine/Ruler.o: src/engine/Ruler.cpp.o

.PHONY : src/engine/Ruler.o

# target to build an object file
src/engine/Ruler.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Ruler.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Ruler.cpp.o
.PHONY : src/engine/Ruler.cpp.o

src/engine/Ruler.i: src/engine/Ruler.cpp.i

.PHONY : src/engine/Ruler.i

# target to preprocess a source file
src/engine/Ruler.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Ruler.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Ruler.cpp.i
.PHONY : src/engine/Ruler.cpp.i

src/engine/Ruler.s: src/engine/Ruler.cpp.s

.PHONY : src/engine/Ruler.s

# target to generate assembly for a file
src/engine/Ruler.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/Ruler.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/Ruler.cpp.s
.PHONY : src/engine/Ruler.cpp.s

src/engine/ShotCommand.o: src/engine/ShotCommand.cpp.o

.PHONY : src/engine/ShotCommand.o

# target to build an object file
src/engine/ShotCommand.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ShotCommand.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ShotCommand.cpp.o
.PHONY : src/engine/ShotCommand.cpp.o

src/engine/ShotCommand.i: src/engine/ShotCommand.cpp.i

.PHONY : src/engine/ShotCommand.i

# target to preprocess a source file
src/engine/ShotCommand.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ShotCommand.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ShotCommand.cpp.i
.PHONY : src/engine/ShotCommand.cpp.i

src/engine/ShotCommand.s: src/engine/ShotCommand.cpp.s

.PHONY : src/engine/ShotCommand.s

# target to generate assembly for a file
src/engine/ShotCommand.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/engine/ShotCommand.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/ShotCommand.cpp.s
.PHONY : src/engine/ShotCommand.cpp.s

src/render/Animation.o: src/render/Animation.cpp.o

.PHONY : src/render/Animation.o

# target to build an object file
src/render/Animation.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Animation.cpp.o
.PHONY : src/render/Animation.cpp.o

src/render/Animation.i: src/render/Animation.cpp.i

.PHONY : src/render/Animation.i

# target to preprocess a source file
src/render/Animation.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Animation.cpp.i
.PHONY : src/render/Animation.cpp.i

src/render/Animation.s: src/render/Animation.cpp.s

.PHONY : src/render/Animation.s

# target to generate assembly for a file
src/render/Animation.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Animation.cpp.s
.PHONY : src/render/Animation.cpp.s

src/render/CharLayer.o: src/render/CharLayer.cpp.o

.PHONY : src/render/CharLayer.o

# target to build an object file
src/render/CharLayer.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/CharLayer.cpp.o
.PHONY : src/render/CharLayer.cpp.o

src/render/CharLayer.i: src/render/CharLayer.cpp.i

.PHONY : src/render/CharLayer.i

# target to preprocess a source file
src/render/CharLayer.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/CharLayer.cpp.i
.PHONY : src/render/CharLayer.cpp.i

src/render/CharLayer.s: src/render/CharLayer.cpp.s

.PHONY : src/render/CharLayer.s

# target to generate assembly for a file
src/render/CharLayer.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/CharLayer.cpp.s
.PHONY : src/render/CharLayer.cpp.s

src/render/LandscapeLayer.o: src/render/LandscapeLayer.cpp.o

.PHONY : src/render/LandscapeLayer.o

# target to build an object file
src/render/LandscapeLayer.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/LandscapeLayer.cpp.o
.PHONY : src/render/LandscapeLayer.cpp.o

src/render/LandscapeLayer.i: src/render/LandscapeLayer.cpp.i

.PHONY : src/render/LandscapeLayer.i

# target to preprocess a source file
src/render/LandscapeLayer.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/LandscapeLayer.cpp.i
.PHONY : src/render/LandscapeLayer.cpp.i

src/render/LandscapeLayer.s: src/render/LandscapeLayer.cpp.s

.PHONY : src/render/LandscapeLayer.s

# target to generate assembly for a file
src/render/LandscapeLayer.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/LandscapeLayer.cpp.s
.PHONY : src/render/LandscapeLayer.cpp.s

src/render/Layer.o: src/render/Layer.cpp.o

.PHONY : src/render/Layer.o

# target to build an object file
src/render/Layer.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Layer.cpp.o
.PHONY : src/render/Layer.cpp.o

src/render/Layer.i: src/render/Layer.cpp.i

.PHONY : src/render/Layer.i

# target to preprocess a source file
src/render/Layer.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Layer.cpp.i
.PHONY : src/render/Layer.cpp.i

src/render/Layer.s: src/render/Layer.cpp.s

.PHONY : src/render/Layer.s

# target to generate assembly for a file
src/render/Layer.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Layer.cpp.s
.PHONY : src/render/Layer.cpp.s

src/render/Missile.o: src/render/Missile.cpp.o

.PHONY : src/render/Missile.o

# target to build an object file
src/render/Missile.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Missile.cpp.o
.PHONY : src/render/Missile.cpp.o

src/render/Missile.i: src/render/Missile.cpp.i

.PHONY : src/render/Missile.i

# target to preprocess a source file
src/render/Missile.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Missile.cpp.i
.PHONY : src/render/Missile.cpp.i

src/render/Missile.s: src/render/Missile.cpp.s

.PHONY : src/render/Missile.s

# target to generate assembly for a file
src/render/Missile.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Missile.cpp.s
.PHONY : src/render/Missile.cpp.s

src/render/MobileLayer.o: src/render/MobileLayer.cpp.o

.PHONY : src/render/MobileLayer.o

# target to build an object file
src/render/MobileLayer.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/MobileLayer.cpp.o
.PHONY : src/render/MobileLayer.cpp.o

src/render/MobileLayer.i: src/render/MobileLayer.cpp.i

.PHONY : src/render/MobileLayer.i

# target to preprocess a source file
src/render/MobileLayer.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/MobileLayer.cpp.i
.PHONY : src/render/MobileLayer.cpp.i

src/render/MobileLayer.s: src/render/MobileLayer.cpp.s

.PHONY : src/render/MobileLayer.s

# target to generate assembly for a file
src/render/MobileLayer.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/MobileLayer.cpp.s
.PHONY : src/render/MobileLayer.cpp.s

src/render/Scene.o: src/render/Scene.cpp.o

.PHONY : src/render/Scene.o

# target to build an object file
src/render/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Scene.cpp.o
.PHONY : src/render/Scene.cpp.o

src/render/Scene.i: src/render/Scene.cpp.i

.PHONY : src/render/Scene.i

# target to preprocess a source file
src/render/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Scene.cpp.i
.PHONY : src/render/Scene.cpp.i

src/render/Scene.s: src/render/Scene.cpp.s

.PHONY : src/render/Scene.s

# target to generate assembly for a file
src/render/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Scene.cpp.s
.PHONY : src/render/Scene.cpp.s

src/render/Shell.o: src/render/Shell.cpp.o

.PHONY : src/render/Shell.o

# target to build an object file
src/render/Shell.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Shell.cpp.o
.PHONY : src/render/Shell.cpp.o

src/render/Shell.i: src/render/Shell.cpp.i

.PHONY : src/render/Shell.i

# target to preprocess a source file
src/render/Shell.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Shell.cpp.i
.PHONY : src/render/Shell.cpp.i

src/render/Shell.s: src/render/Shell.cpp.s

.PHONY : src/render/Shell.s

# target to generate assembly for a file
src/render/Shell.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Shell.cpp.s
.PHONY : src/render/Shell.cpp.s

src/render/Surface.o: src/render/Surface.cpp.o

.PHONY : src/render/Surface.o

# target to build an object file
src/render/Surface.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Surface.cpp.o
.PHONY : src/render/Surface.cpp.o

src/render/Surface.i: src/render/Surface.cpp.i

.PHONY : src/render/Surface.i

# target to preprocess a source file
src/render/Surface.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Surface.cpp.i
.PHONY : src/render/Surface.cpp.i

src/render/Surface.s: src/render/Surface.cpp.s

.PHONY : src/render/Surface.s

# target to generate assembly for a file
src/render/Surface.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Surface.cpp.s
.PHONY : src/render/Surface.cpp.s

src/render/SurfaceSFML.o: src/render/SurfaceSFML.cpp.o

.PHONY : src/render/SurfaceSFML.o

# target to build an object file
src/render/SurfaceSFML.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/SurfaceSFML.cpp.o
.PHONY : src/render/SurfaceSFML.cpp.o

src/render/SurfaceSFML.i: src/render/SurfaceSFML.cpp.i

.PHONY : src/render/SurfaceSFML.i

# target to preprocess a source file
src/render/SurfaceSFML.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/SurfaceSFML.cpp.i
.PHONY : src/render/SurfaceSFML.cpp.i

src/render/SurfaceSFML.s: src/render/SurfaceSFML.cpp.s

.PHONY : src/render/SurfaceSFML.s

# target to generate assembly for a file
src/render/SurfaceSFML.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/SurfaceSFML.cpp.s
.PHONY : src/render/SurfaceSFML.cpp.s

src/render/Tile.o: src/render/Tile.cpp.o

.PHONY : src/render/Tile.o

# target to build an object file
src/render/Tile.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Tile.cpp.o
.PHONY : src/render/Tile.cpp.o

src/render/Tile.i: src/render/Tile.cpp.i

.PHONY : src/render/Tile.i

# target to preprocess a source file
src/render/Tile.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Tile.cpp.i
.PHONY : src/render/Tile.cpp.i

src/render/Tile.s: src/render/Tile.cpp.s

.PHONY : src/render/Tile.s

# target to generate assembly for a file
src/render/Tile.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/render/Tile.cpp.s
.PHONY : src/render/Tile.cpp.s

src/server/AbstractService.o: src/server/AbstractService.cpp.o

.PHONY : src/server/AbstractService.o

# target to build an object file
src/server/AbstractService.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/AbstractService.cpp.o
.PHONY : src/server/AbstractService.cpp.o

src/server/AbstractService.i: src/server/AbstractService.cpp.i

.PHONY : src/server/AbstractService.i

# target to preprocess a source file
src/server/AbstractService.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/AbstractService.cpp.i
.PHONY : src/server/AbstractService.cpp.i

src/server/AbstractService.s: src/server/AbstractService.cpp.s

.PHONY : src/server/AbstractService.s

# target to generate assembly for a file
src/server/AbstractService.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/AbstractService.cpp.s
.PHONY : src/server/AbstractService.cpp.s

src/server/GameServer.o: src/server/GameServer.cpp.o

.PHONY : src/server/GameServer.o

# target to build an object file
src/server/GameServer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/GameServer.cpp.o
.PHONY : src/server/GameServer.cpp.o

src/server/GameServer.i: src/server/GameServer.cpp.i

.PHONY : src/server/GameServer.i

# target to preprocess a source file
src/server/GameServer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/GameServer.cpp.i
.PHONY : src/server/GameServer.cpp.i

src/server/GameServer.s: src/server/GameServer.cpp.s

.PHONY : src/server/GameServer.s

# target to generate assembly for a file
src/server/GameServer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/GameServer.cpp.s
.PHONY : src/server/GameServer.cpp.s

src/server/ServiceException.o: src/server/ServiceException.cpp.o

.PHONY : src/server/ServiceException.o

# target to build an object file
src/server/ServiceException.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ServiceException.cpp.o
.PHONY : src/server/ServiceException.cpp.o

src/server/ServiceException.i: src/server/ServiceException.cpp.i

.PHONY : src/server/ServiceException.i

# target to preprocess a source file
src/server/ServiceException.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ServiceException.cpp.i
.PHONY : src/server/ServiceException.cpp.i

src/server/ServiceException.s: src/server/ServiceException.cpp.s

.PHONY : src/server/ServiceException.s

# target to generate assembly for a file
src/server/ServiceException.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ServiceException.cpp.s
.PHONY : src/server/ServiceException.cpp.s

src/server/ServicesManager.o: src/server/ServicesManager.cpp.o

.PHONY : src/server/ServicesManager.o

# target to build an object file
src/server/ServicesManager.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ServicesManager.cpp.o
.PHONY : src/server/ServicesManager.cpp.o

src/server/ServicesManager.i: src/server/ServicesManager.cpp.i

.PHONY : src/server/ServicesManager.i

# target to preprocess a source file
src/server/ServicesManager.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ServicesManager.cpp.i
.PHONY : src/server/ServicesManager.cpp.i

src/server/ServicesManager.s: src/server/ServicesManager.cpp.s

.PHONY : src/server/ServicesManager.s

# target to generate assembly for a file
src/server/ServicesManager.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ServicesManager.cpp.s
.PHONY : src/server/ServicesManager.cpp.s

src/server/UserDB.o: src/server/UserDB.cpp.o

.PHONY : src/server/UserDB.o

# target to build an object file
src/server/UserDB.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/UserDB.cpp.o
.PHONY : src/server/UserDB.cpp.o

src/server/UserDB.i: src/server/UserDB.cpp.i

.PHONY : src/server/UserDB.i

# target to preprocess a source file
src/server/UserDB.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/UserDB.cpp.i
.PHONY : src/server/UserDB.cpp.i

src/server/UserDB.s: src/server/UserDB.cpp.s

.PHONY : src/server/UserDB.s

# target to generate assembly for a file
src/server/UserDB.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/UserDB.cpp.s
.PHONY : src/server/UserDB.cpp.s

src/server/UserService.o: src/server/UserService.cpp.o

.PHONY : src/server/UserService.o

# target to build an object file
src/server/UserService.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/UserService.cpp.o
.PHONY : src/server/UserService.cpp.o

src/server/UserService.i: src/server/UserService.cpp.i

.PHONY : src/server/UserService.i

# target to preprocess a source file
src/server/UserService.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/UserService.cpp.i
.PHONY : src/server/UserService.cpp.i

src/server/UserService.s: src/server/UserService.cpp.s

.PHONY : src/server/UserService.s

# target to generate assembly for a file
src/server/UserService.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/UserService.cpp.s
.PHONY : src/server/UserService.cpp.s

src/server/main.o: src/server/main.cpp.o

.PHONY : src/server/main.o

# target to build an object file
src/server/main.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.o
.PHONY : src/server/main.cpp.o

src/server/main.i: src/server/main.cpp.i

.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s

.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

src/state/Element.o: src/state/Element.cpp.o

.PHONY : src/state/Element.o

# target to build an object file
src/state/Element.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Element.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Element.cpp.o
.PHONY : src/state/Element.cpp.o

src/state/Element.i: src/state/Element.cpp.i

.PHONY : src/state/Element.i

# target to preprocess a source file
src/state/Element.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Element.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Element.cpp.i
.PHONY : src/state/Element.cpp.i

src/state/Element.s: src/state/Element.cpp.s

.PHONY : src/state/Element.s

# target to generate assembly for a file
src/state/Element.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Element.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Element.cpp.s
.PHONY : src/state/Element.cpp.s

src/state/ElementEvent.o: src/state/ElementEvent.cpp.o

.PHONY : src/state/ElementEvent.o

# target to build an object file
src/state/ElementEvent.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementEvent.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/ElementEvent.cpp.o
.PHONY : src/state/ElementEvent.cpp.o

src/state/ElementEvent.i: src/state/ElementEvent.cpp.i

.PHONY : src/state/ElementEvent.i

# target to preprocess a source file
src/state/ElementEvent.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementEvent.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/ElementEvent.cpp.i
.PHONY : src/state/ElementEvent.cpp.i

src/state/ElementEvent.s: src/state/ElementEvent.cpp.s

.PHONY : src/state/ElementEvent.s

# target to generate assembly for a file
src/state/ElementEvent.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementEvent.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/ElementEvent.cpp.s
.PHONY : src/state/ElementEvent.cpp.s

src/state/ElementGrid.o: src/state/ElementGrid.cpp.o

.PHONY : src/state/ElementGrid.o

# target to build an object file
src/state/ElementGrid.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementGrid.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/ElementGrid.cpp.o
.PHONY : src/state/ElementGrid.cpp.o

src/state/ElementGrid.i: src/state/ElementGrid.cpp.i

.PHONY : src/state/ElementGrid.i

# target to preprocess a source file
src/state/ElementGrid.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementGrid.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/ElementGrid.cpp.i
.PHONY : src/state/ElementGrid.cpp.i

src/state/ElementGrid.s: src/state/ElementGrid.cpp.s

.PHONY : src/state/ElementGrid.s

# target to generate assembly for a file
src/state/ElementGrid.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementGrid.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/ElementGrid.cpp.s
.PHONY : src/state/ElementGrid.cpp.s

src/state/ElementList.o: src/state/ElementList.cpp.o

.PHONY : src/state/ElementList.o

# target to build an object file
src/state/ElementList.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementList.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/ElementList.cpp.o
.PHONY : src/state/ElementList.cpp.o

src/state/ElementList.i: src/state/ElementList.cpp.i

.PHONY : src/state/ElementList.i

# target to preprocess a source file
src/state/ElementList.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementList.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/ElementList.cpp.i
.PHONY : src/state/ElementList.cpp.i

src/state/ElementList.s: src/state/ElementList.cpp.s

.PHONY : src/state/ElementList.s

# target to generate assembly for a file
src/state/ElementList.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementList.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/ElementList.cpp.s
.PHONY : src/state/ElementList.cpp.s

src/state/Observable.o: src/state/Observable.cpp.o

.PHONY : src/state/Observable.o

# target to build an object file
src/state/Observable.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Observable.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Observable.cpp.o
.PHONY : src/state/Observable.cpp.o

src/state/Observable.i: src/state/Observable.cpp.i

.PHONY : src/state/Observable.i

# target to preprocess a source file
src/state/Observable.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Observable.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Observable.cpp.i
.PHONY : src/state/Observable.cpp.i

src/state/Observable.s: src/state/Observable.cpp.s

.PHONY : src/state/Observable.s

# target to generate assembly for a file
src/state/Observable.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Observable.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Observable.cpp.s
.PHONY : src/state/Observable.cpp.s

src/state/Obstacle.o: src/state/Obstacle.cpp.o

.PHONY : src/state/Obstacle.o

# target to build an object file
src/state/Obstacle.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Obstacle.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Obstacle.cpp.o
.PHONY : src/state/Obstacle.cpp.o

src/state/Obstacle.i: src/state/Obstacle.cpp.i

.PHONY : src/state/Obstacle.i

# target to preprocess a source file
src/state/Obstacle.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Obstacle.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Obstacle.cpp.i
.PHONY : src/state/Obstacle.cpp.i

src/state/Obstacle.s: src/state/Obstacle.cpp.s

.PHONY : src/state/Obstacle.s

# target to generate assembly for a file
src/state/Obstacle.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Obstacle.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Obstacle.cpp.s
.PHONY : src/state/Obstacle.cpp.s

src/state/ProjectileEvent.o: src/state/ProjectileEvent.cpp.o

.PHONY : src/state/ProjectileEvent.o

# target to build an object file
src/state/ProjectileEvent.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ProjectileEvent.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/ProjectileEvent.cpp.o
.PHONY : src/state/ProjectileEvent.cpp.o

src/state/ProjectileEvent.i: src/state/ProjectileEvent.cpp.i

.PHONY : src/state/ProjectileEvent.i

# target to preprocess a source file
src/state/ProjectileEvent.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ProjectileEvent.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/ProjectileEvent.cpp.i
.PHONY : src/state/ProjectileEvent.cpp.i

src/state/ProjectileEvent.s: src/state/ProjectileEvent.cpp.s

.PHONY : src/state/ProjectileEvent.s

# target to generate assembly for a file
src/state/ProjectileEvent.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ProjectileEvent.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/ProjectileEvent.cpp.s
.PHONY : src/state/ProjectileEvent.cpp.s

src/state/Space.o: src/state/Space.cpp.o

.PHONY : src/state/Space.o

# target to build an object file
src/state/Space.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Space.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Space.cpp.o
.PHONY : src/state/Space.cpp.o

src/state/Space.i: src/state/Space.cpp.i

.PHONY : src/state/Space.i

# target to preprocess a source file
src/state/Space.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Space.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Space.cpp.i
.PHONY : src/state/Space.cpp.i

src/state/Space.s: src/state/Space.cpp.s

.PHONY : src/state/Space.s

# target to generate assembly for a file
src/state/Space.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Space.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Space.cpp.s
.PHONY : src/state/Space.cpp.s

src/state/State.o: src/state/State.cpp.o

.PHONY : src/state/State.o

# target to build an object file
src/state/State.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/State.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/State.cpp.o
.PHONY : src/state/State.cpp.o

src/state/State.i: src/state/State.cpp.i

.PHONY : src/state/State.i

# target to preprocess a source file
src/state/State.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/State.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/State.cpp.i
.PHONY : src/state/State.cpp.i

src/state/State.s: src/state/State.cpp.s

.PHONY : src/state/State.s

# target to generate assembly for a file
src/state/State.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/State.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/State.cpp.s
.PHONY : src/state/State.cpp.s

src/state/StateEvent.o: src/state/StateEvent.cpp.o

.PHONY : src/state/StateEvent.o

# target to build an object file
src/state/StateEvent.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/StateEvent.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/StateEvent.cpp.o
.PHONY : src/state/StateEvent.cpp.o

src/state/StateEvent.i: src/state/StateEvent.cpp.i

.PHONY : src/state/StateEvent.i

# target to preprocess a source file
src/state/StateEvent.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/StateEvent.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/StateEvent.cpp.i
.PHONY : src/state/StateEvent.cpp.i

src/state/StateEvent.s: src/state/StateEvent.cpp.s

.PHONY : src/state/StateEvent.s

# target to generate assembly for a file
src/state/StateEvent.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/StateEvent.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/StateEvent.cpp.s
.PHONY : src/state/StateEvent.cpp.s

src/state/StaticElement.o: src/state/StaticElement.cpp.o

.PHONY : src/state/StaticElement.o

# target to build an object file
src/state/StaticElement.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/StaticElement.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/StaticElement.cpp.o
.PHONY : src/state/StaticElement.cpp.o

src/state/StaticElement.i: src/state/StaticElement.cpp.i

.PHONY : src/state/StaticElement.i

# target to preprocess a source file
src/state/StaticElement.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/StaticElement.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/StaticElement.cpp.i
.PHONY : src/state/StaticElement.cpp.i

src/state/StaticElement.s: src/state/StaticElement.cpp.s

.PHONY : src/state/StaticElement.s

# target to generate assembly for a file
src/state/StaticElement.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/StaticElement.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/StaticElement.cpp.s
.PHONY : src/state/StaticElement.cpp.s

src/state/Tank.o: src/state/Tank.cpp.o

.PHONY : src/state/Tank.o

# target to build an object file
src/state/Tank.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Tank.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Tank.cpp.o
.PHONY : src/state/Tank.cpp.o

src/state/Tank.i: src/state/Tank.cpp.i

.PHONY : src/state/Tank.i

# target to preprocess a source file
src/state/Tank.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Tank.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Tank.cpp.i
.PHONY : src/state/Tank.cpp.i

src/state/Tank.s: src/state/Tank.cpp.s

.PHONY : src/state/Tank.s

# target to generate assembly for a file
src/state/Tank.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Tank.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/state/Tank.cpp.s
.PHONY : src/state/Tank.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... run"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... extern/jsoncpp-0.10.5/dist/jsoncpp.o"
	@echo "... extern/jsoncpp-0.10.5/dist/jsoncpp.i"
	@echo "... extern/jsoncpp-0.10.5/dist/jsoncpp.s"
	@echo "... src/ai/AI.o"
	@echo "... src/ai/AI.i"
	@echo "... src/ai/AI.s"
	@echo "... src/ai/DistanceUtility.o"
	@echo "... src/ai/DistanceUtility.i"
	@echo "... src/ai/DistanceUtility.s"
	@echo "... src/ai/DumbAI.o"
	@echo "... src/ai/DumbAI.i"
	@echo "... src/ai/DumbAI.s"
	@echo "... src/ai/EvolvedAI.o"
	@echo "... src/ai/EvolvedAI.i"
	@echo "... src/ai/EvolvedAI.s"
	@echo "... src/ai/Gardener.o"
	@echo "... src/ai/Gardener.i"
	@echo "... src/ai/Gardener.s"
	@echo "... src/ai/HeuristicAI.o"
	@echo "... src/ai/HeuristicAI.i"
	@echo "... src/ai/HeuristicAI.s"
	@echo "... src/ai/TreeAI.o"
	@echo "... src/ai/TreeAI.i"
	@echo "... src/ai/TreeAI.s"
	@echo "... src/client/Button.o"
	@echo "... src/client/Button.i"
	@echo "... src/client/Button.s"
	@echo "... src/client/CacheStateObserver.o"
	@echo "... src/client/CacheStateObserver.i"
	@echo "... src/client/CacheStateObserver.s"
	@echo "... src/client/Pilote.o"
	@echo "... src/client/Pilote.i"
	@echo "... src/client/Pilote.s"
	@echo "... src/client/PiloteSFML.o"
	@echo "... src/client/PiloteSFML.i"
	@echo "... src/client/PiloteSFML.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/engine/Action.o"
	@echo "... src/engine/Action.i"
	@echo "... src/engine/Action.s"
	@echo "... src/engine/ActionDirection.o"
	@echo "... src/engine/ActionDirection.i"
	@echo "... src/engine/ActionDirection.s"
	@echo "... src/engine/ActionListTurn.o"
	@echo "... src/engine/ActionListTurn.i"
	@echo "... src/engine/ActionListTurn.s"
	@echo "... src/engine/ActionMove.o"
	@echo "... src/engine/ActionMove.i"
	@echo "... src/engine/ActionMove.s"
	@echo "... src/engine/ActionShot.o"
	@echo "... src/engine/ActionShot.i"
	@echo "... src/engine/ActionShot.s"
	@echo "... src/engine/Command.o"
	@echo "... src/engine/Command.i"
	@echo "... src/engine/Command.s"
	@echo "... src/engine/CommandSet.o"
	@echo "... src/engine/CommandSet.i"
	@echo "... src/engine/CommandSet.s"
	@echo "... src/engine/DirectionCommand.o"
	@echo "... src/engine/DirectionCommand.i"
	@echo "... src/engine/DirectionCommand.s"
	@echo "... src/engine/EndTurnCommand.o"
	@echo "... src/engine/EndTurnCommand.i"
	@echo "... src/engine/EndTurnCommand.s"
	@echo "... src/engine/Engine.o"
	@echo "... src/engine/Engine.i"
	@echo "... src/engine/Engine.s"
	@echo "... src/engine/LoadCommand.o"
	@echo "... src/engine/LoadCommand.i"
	@echo "... src/engine/LoadCommand.s"
	@echo "... src/engine/ModeCommand.o"
	@echo "... src/engine/ModeCommand.i"
	@echo "... src/engine/ModeCommand.s"
	@echo "... src/engine/MoveCommand.o"
	@echo "... src/engine/MoveCommand.i"
	@echo "... src/engine/MoveCommand.s"
	@echo "... src/engine/Record.o"
	@echo "... src/engine/Record.i"
	@echo "... src/engine/Record.s"
	@echo "... src/engine/Ruler.o"
	@echo "... src/engine/Ruler.i"
	@echo "... src/engine/Ruler.s"
	@echo "... src/engine/ShotCommand.o"
	@echo "... src/engine/ShotCommand.i"
	@echo "... src/engine/ShotCommand.s"
	@echo "... src/render/Animation.o"
	@echo "... src/render/Animation.i"
	@echo "... src/render/Animation.s"
	@echo "... src/render/CharLayer.o"
	@echo "... src/render/CharLayer.i"
	@echo "... src/render/CharLayer.s"
	@echo "... src/render/LandscapeLayer.o"
	@echo "... src/render/LandscapeLayer.i"
	@echo "... src/render/LandscapeLayer.s"
	@echo "... src/render/Layer.o"
	@echo "... src/render/Layer.i"
	@echo "... src/render/Layer.s"
	@echo "... src/render/Missile.o"
	@echo "... src/render/Missile.i"
	@echo "... src/render/Missile.s"
	@echo "... src/render/MobileLayer.o"
	@echo "... src/render/MobileLayer.i"
	@echo "... src/render/MobileLayer.s"
	@echo "... src/render/Scene.o"
	@echo "... src/render/Scene.i"
	@echo "... src/render/Scene.s"
	@echo "... src/render/Shell.o"
	@echo "... src/render/Shell.i"
	@echo "... src/render/Shell.s"
	@echo "... src/render/Surface.o"
	@echo "... src/render/Surface.i"
	@echo "... src/render/Surface.s"
	@echo "... src/render/SurfaceSFML.o"
	@echo "... src/render/SurfaceSFML.i"
	@echo "... src/render/SurfaceSFML.s"
	@echo "... src/render/Tile.o"
	@echo "... src/render/Tile.i"
	@echo "... src/render/Tile.s"
	@echo "... src/server/AbstractService.o"
	@echo "... src/server/AbstractService.i"
	@echo "... src/server/AbstractService.s"
	@echo "... src/server/GameServer.o"
	@echo "... src/server/GameServer.i"
	@echo "... src/server/GameServer.s"
	@echo "... src/server/ServiceException.o"
	@echo "... src/server/ServiceException.i"
	@echo "... src/server/ServiceException.s"
	@echo "... src/server/ServicesManager.o"
	@echo "... src/server/ServicesManager.i"
	@echo "... src/server/ServicesManager.s"
	@echo "... src/server/UserDB.o"
	@echo "... src/server/UserDB.i"
	@echo "... src/server/UserDB.s"
	@echo "... src/server/UserService.o"
	@echo "... src/server/UserService.i"
	@echo "... src/server/UserService.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
	@echo "... src/state/Element.o"
	@echo "... src/state/Element.i"
	@echo "... src/state/Element.s"
	@echo "... src/state/ElementEvent.o"
	@echo "... src/state/ElementEvent.i"
	@echo "... src/state/ElementEvent.s"
	@echo "... src/state/ElementGrid.o"
	@echo "... src/state/ElementGrid.i"
	@echo "... src/state/ElementGrid.s"
	@echo "... src/state/ElementList.o"
	@echo "... src/state/ElementList.i"
	@echo "... src/state/ElementList.s"
	@echo "... src/state/Observable.o"
	@echo "... src/state/Observable.i"
	@echo "... src/state/Observable.s"
	@echo "... src/state/Obstacle.o"
	@echo "... src/state/Obstacle.i"
	@echo "... src/state/Obstacle.s"
	@echo "... src/state/ProjectileEvent.o"
	@echo "... src/state/ProjectileEvent.i"
	@echo "... src/state/ProjectileEvent.s"
	@echo "... src/state/Space.o"
	@echo "... src/state/Space.i"
	@echo "... src/state/Space.s"
	@echo "... src/state/State.o"
	@echo "... src/state/State.i"
	@echo "... src/state/State.s"
	@echo "... src/state/StateEvent.o"
	@echo "... src/state/StateEvent.i"
	@echo "... src/state/StateEvent.s"
	@echo "... src/state/StaticElement.o"
	@echo "... src/state/StaticElement.i"
	@echo "... src/state/StaticElement.s"
	@echo "... src/state/Tank.o"
	@echo "... src/state/Tank.i"
	@echo "... src/state/Tank.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

