// Generated by dia2code
#ifndef ENGINE__ACTION__H
#define ENGINE__ACTION__H

#include "../state.h"
namespace engine {

  /// class Action - 
  class Action {
    // Operations
  public:
    Action ();
    virtual void apply (state::State* s) = 0;
    virtual void undo (state::State* s) = 0;
  };

};

#endif
