// Generated by dia2code
#ifndef ENGINE__ACTIONLISTTURN__H
#define ENGINE__ACTIONLISTTURN__H

#include <vector>
#include "../state.h"

namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class ActionListTurn - //liste les actions faite sur le tour
  class ActionListTurn {
    // Associations
    // Attributes
  protected:
    std::vector<Action*> actions;
    state::State* state;
    // Operations
  public:
    void apply ();
    void undo ();
    void addAction (Action* a);
    ActionListTurn (state::State* s);
  };

};

#endif
