// Generated by dia2code
#ifndef ENGINE__ACTIONSHOT__H
#define ENGINE__ACTIONSHOT__H

#include "state/State.h"

namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class ActionShot - 
  class ActionShot : public engine::Action {
    // Attributes
  protected:
    int damage;
    int xImpact;
    int yImpact;
    int yMax;
    int characterTarget;
    int character;
    bool displayPv;
    // Operations
  public:
    ActionShot (int character, int characterTarget, int damage, int xImpact, int yImpact, int yMax, bool displayPv = false);
    void apply (state::State* s, bool notify);
    void undo (state::State* s);
  };

};

#endif
