// Generated by dia2code
#ifndef ENGINE__ACTIONDIRECTION__H
#define ENGINE__ACTIONDIRECTION__H

#include "state/Orientation.h"
#include "state/State.h"

namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class ActionDirection - 
  class ActionDirection : public engine::Action {
    // Attributes
  protected:
    state::Orientation Newdirection;
    int character;
    state::Orientation OldDirection;
    // Operations
  public:
    ActionDirection (state::Orientation direction, int character);
    void apply (state::State* s);
    void undo (state::State* s);
  };

};

#endif
