// Generated by dia2code
#ifndef ENGINE__COMMANDCATEGORY__H
#define ENGINE__COMMANDCATEGORY__H


namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  enum CommandCategory {
    MAIN_CATEGORY = 100,
    END_CATEGORY  = 150,
    MODE_CATEGORY = 200,
    MOVE_CATEGORY = 300,
    VIEW_CATEGORY = 400,
    SHOT_CATEGORY = 500
  };

};

#endif
