// Generated by dia2code
#ifndef ENGINE__COMMANDSET__H
#define ENGINE__COMMANDSET__H

#include <map>

namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class CommandSet - 
  class CommandSet {
    // Associations
    // Attributes
  protected:
    std::map<int,Command*> commands;
    // Operations
  public:
    ~CommandSet ();
    int size () const;
    void add (Command* command);
    Command* get (int category) const;
    void clear ();
  };

};

#endif
