// Generated by dia2code
#ifndef ENGINE__ENGINEMODE__H
#define ENGINE__ENGINEMODE__H


namespace engine {

  enum EngineMode {
    close     = 0,
    play     = 1,
    AI     = 2,
    replay     = 3,
    Finish     = 4
  };

};

#endif
