// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include "../state.h"
#include <mutex>

namespace engine {
  class CommandSet;
  class Command;
  class Ruler;
}

#include "EngineMode.h"
#include "Ruler.h"
#include "CommandSet.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    engine::EngineMode mode;
    engine::Ruler ruler;
    // Attributes
  protected:
    CommandSet* currentcommands;
    CommandSet* waitingcommands;
    int charTurn;
    state::State* state;
    mutable std::mutex commands_mutex;
    // Operations
  public:
    Engine (state::State* s);
    ~Engine ();
    void addCommand (Command* cmd);
    void setMode (EngineMode m);
    void setcharTurn (int c);
    int getcharTurn () const;
    Ruler* getRuler ();
    void endTurn ();
    void swapCommands ();
    void update ();
  };

};

#endif
