// Generated by dia2code
#ifndef ENGINE__ENGINEMODE__H
#define ENGINE__ENGINEMODE__H


namespace engine {

  enum EngineMode {
    play     = 1,
    pause     = 2,
    close     = 0,
    animation     = 3,
    victoire     = 4,
    defaite     = 5
  };

};

#endif
