// Generated by dia2code
#ifndef ENGINE__MODECOMMAND__H
#define ENGINE__MODECOMMAND__H


namespace engine {
  class Command;
}

#include "EngineMode.h"
#include "Command.h"

namespace engine {

  /// class ModeCommand - 
  class ModeCommand : public engine::Command {
    // Attributes
  protected:
    EngineMode mode;
    // Operations
  public:
    EngineMode getMode () const;
    int getCategory () const;
    ModeCommand (EngineMode mode);
    int getCharacter () const;
  };

};

#endif
