// Generated by dia2code
#ifndef ENGINE__MOVECOMMAND__H
#define ENGINE__MOVECOMMAND__H

#include "../state.h"
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class MoveCommand - 
  class MoveCommand : public engine::Command {
    // Attributes
  protected:
    int character;
    int Xmove;
    int Ymove;
    // Operations
  public:
    MoveCommand (int c, state::Orientation d);
    int getCharacter () const;
    int getCategory () const;
    int getXmove () const;
    int getYmove () const;
  };

};

#endif
