// Generated by dia2code
#ifndef ENGINE__RULER__H
#define ENGINE__RULER__H

#include "../state.h"
namespace engine {
  class ActionListTurn;
  class CommandSet;
}

#include "EngineMode.h"
#include "ActionListTurn.h"

namespace engine {

  /// class Ruler - //crée les actions à partir des commandes : aller à droite tourne le char vers la droite et bouge à droite (2 actions donc)
  class Ruler {
    // Associations
    // Attributes
  protected:
    ActionListTurn* actions;
    state::State* state;
    CommandSet* cmd;
    // Operations
  public:
    Ruler (state::State* const state);
    void setCommandSet (CommandSet* const cmd);
    void setActions (ActionListTurn* const actions);
    void apply ();
    void impleRule (EngineMode mode);
  };

};

#endif
