// Generated by dia2code
#ifndef ENGINE__SHOTCOMMAND__H
#define ENGINE__SHOTCOMMAND__H


namespace engine {

  /// class ShotCommand - 
  class ShotCommand {
    // Attributes
  protected:
    int character;
    int power;
    // Operations
  public:
    ShotCommand (int c, int p);
    int getCharacter () const;
    int getPower () const;
    int getCategory () const;
  };

};

#endif
