// Generated by dia2code
#ifndef RENDER__ANIMATION__H
#define RENDER__ANIMATION__H


namespace render {
  class Tile;
}

namespace render {

  /// class Animation - Give the method to draw the next tile in a animation
  class Animation {
    // Attributes
  protected:
    bool rightDirection;
    int countTimeExplosion;
    // Operations
  public:
    virtual ~Animation ();
    virtual bool setNextTile (Tile* tile) = 0;
  };

};

#endif
