// Generated by dia2code
#ifndef RENDER__CHARLAYER__H
#define RENDER__CHARLAYER__H

#include "../state.h"
#include "state/StateEvent.h"

namespace state {
  class StateEvent;
};
namespace render {
  class Layer;
}

#include "Layer.h"

namespace render {

  /// class CharLayer - 
  class CharLayer : public render::Layer {
    // Attributes
  protected:
    int XChar;
    // Operations
  public:
    void stateChanged (const state::StateEvent& e);
    void setXChar (int x);
  };

};

#endif
