// Generated by dia2code
#ifndef RENDER__LANDSCAPELAYER__H
#define RENDER__LANDSCAPELAYER__H

#include "../state.h"
#include "state/StateEvent.h"

namespace state {
  class StateEvent;
};
namespace render {
  class Layer;
}

#include "Layer.h"

namespace render {

  /// class LandscapeLayer - 
  class LandscapeLayer : public render::Layer {
    // Operations
  public:
    void stateChanged (const state::StateEvent& e);
  };

};

#endif
