// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <vector>
#include "../state.h"
namespace render {
  class Surface;
  class Tile;
}

#include "Tile.h"
#include "Surface.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
  protected:
    Surface* surface;
    std::vector<Tile*> tiles;
    // Operations
  public:
    Layer ();
    ~Layer ();
    void setSurface (Surface* surface);
    void setTile (Tile* tile);
    Tile getTile (int i);
    void update ();
    void elementToTiles (const state::ElementList* list);
  };

};

#endif
