// Generated by dia2code
#ifndef RENDER__MOBILELAYER__H
#define RENDER__MOBILELAYER__H

#include "../state.h"
#include "state/StateEvent.h"

namespace state {
  class StateEvent;
};
namespace render {
  class Layer;
}

#include "Layer.h"

namespace render {

  /// class MobileLayer - 
  class MobileLayer : public render::Layer {
    // Operations
  public:
    void stateChanged (const state::StateEvent& e);
  };

};

#endif
