// Generated by dia2code
#ifndef RENDER__MOBILELAYER__H
#define RENDER__MOBILELAYER__H


namespace render {
  class Layer;
}

#include "Layer.h"

namespace render {

  /// class MobileLayer - 
  class MobileLayer : public render::Layer {
    // Operations
  public:
    void applyStateChanged ();
  };

};

#endif
