// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <vector>
#include "../state.h"
#include "state/StateEvent.h"

namespace render {
  class Layer;
  class Surface;
};
namespace state {
  class StateEvent;
  class StateObserver;
}

#include "state/StateObserver.h"
#include "Layer.h"

namespace render {

  /// class Scene - height and width is for the window
  class Scene : public state::StateObserver {
    // Associations
    // Attributes
  protected:
    std::vector<Layer*> layers;
    int height;
    int width;
    // Operations
  public:
    Scene ();
    ~Scene ();
    int getLayerCount () const;
    void setSurface (int idx, Surface* surface);
    void setLayer (int idx, Layer* layer);
    void update ();
    int getHeight () const;
    int getWidth () const;
    void stateChanged (const state::StateEvent& e);
  };

};

#endif
