// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include "render.h"

namespace render {

  /// class Scene - 
  class Scene {
    // Associations
    // Attributes
  protected:
    int width;
    int height;
    std::vector<Layer*> layers;
    // Operations
  public:
    Scene ();
    ~Scene ();
    int const getWidth ();
    int const getHeight ();
    int const getLayerCount ();
    void setLayer (int idx, Surface* surface);
    void setLevel (const state* s);
  };

};

#endif
