// Generated by dia2code
#ifndef RENDER__SHELL__H
#define RENDER__SHELL__H


namespace render {
  class Tile;
  class Animation;
}

#include "Animation.h"

namespace render {

  /// class Shell - 
  class Shell : public render::Animation {
    // Attributes
  protected:
    int xEnd;
    // Operations
  public:
    Shell (int xEnd, bool rightDirection);
    int getXEnd () const;
    bool setNextTile (Tile* tile);
  };

};

#endif
