// Generated by dia2code
#ifndef RENDER__SURFACESFML__H
#define RENDER__SURFACESFML__H

#include "render.h"

namespace render {

  /// class SurfaceSFML - 
  class SurfaceSFML : public render::Surface {
    // Attributes
  protected:
    sf::Texture texture;
    std::vector<Tile*> tiles;
    int nSprite;
    // Operations
  public:
    virtual void loadTexture (const char* image_file, int x, int y);
    virtual void clear ();
    virtual void setSpriteCount (int n);
    virtual void setSpriteTexture (int i, const Tile* tile);
  };

};

#endif
