// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H

#include <vector>

namespace render {
  class Tile;
}

#include "Tile.h"

namespace render {

  /// class Surface - API to the graphic interface
  class Surface {
    // Operations
  public:
    Surface ();
    virtual void loadTexture (const char* image_file) = 0;
    virtual void clear () = 0;
    virtual void setSprite (const std::vector<Tile> tile) = 0;
    virtual void setSpriteNum (int idx, Tile tile) = 0;
  };

};

#endif
