// Generated by dia2code
#ifndef RENDER__SURFACESFML__H
#define RENDER__SURFACESFML__H

#include <vector>

namespace render {
  class Tile;
  class Surface;
}

#include "Surface.h"

namespace render {

  /// class SurfaceSFML - 
  class SurfaceSFML : public render::Surface {
    // Attributes
  protected:
    sf::Texture texture;
    std::vector<sf::Sprite*> sprites;
    int nSprite;
    // Operations
  public:
    virtual void loadTexture (const char* image_file);
    virtual void clear ();
    virtual void setSpriteCount (int n);
    virtual void setSprite (const std::vector<Tile*> tile);
    std::vector<sf::Sprite*> getSprites () const;
  };

};

#endif
