// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include "state/State.h"
#include "engine/CommandSet.h"

namespace ai {

  /// class AI - Abstract class for AI
  class AI {
    // Attributes
  protected:
    state::State* state;
    int character;
    // Operations
  public:
    AI (state::State* state, int character);
    ~AI ();
    virtual void run (engine::CommandSet& commands) = 0;
    int getCharacter () const;
    state::State* getState ();
  };

};

#endif
