// Generated by dia2code
#ifndef AI__DUMBAI__H
#define AI__DUMBAI__H

#include "state/State.h"
#include "state/StateEvent.h"

namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class DumbAI - 
  class DumbAI : public ai::AI {
    // Operations
  public:
    DumbAI (const state::State& mainState);
    void dumbMove (int idx, engine::CommandSet& commands);
    void run (engine::CommandSet& commands);
    void stateChanged (const state::StateEvent& e);
  };

};

#endif
