// Generated by dia2code
#ifndef AI__DUMBAI__H
#define AI__DUMBAI__H

#include "state/State.h"
#include "engine/CommandSet.h"

namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class DumbAI - The most basic AI. Choice commands randomly
  class DumbAI : public ai::AI {
    // Operations
  public:
    DumbAI (const state::State* state, int character);
    void run (engine::CommandSet& commands);
  };

};

#endif
