// Generated by dia2code
#ifndef AI__GARDENER__H
#define AI__GARDENER__H

#include <vector>
#include "state/State.h"

namespace ai {
  class Node;
  class SearchTree;
}

#include "SearchTree.h"

namespace ai {

  /// class Gardener - 
  class Gardener {
    // Associations
    ai::SearchTree tree;
    // Attributes
  protected:
    std::vector<Node*> nodeWarehouse;
    int depthMax;
    state::State* state;
    engine::Ruler* ruler;
<<<<<<< HEAD
=======
    int character;
    int ActualpvMe;
    int ActualpvOther;
>>>>>>> 2d3a897b584d7da935c8de7d64ddfd7138481702
    // Operations
  public:
    Gardener (int depthMax, state::State* state);
    int minimax_rec (Node* Node);
    int minimax_rec_max (Node* Node);
    int minimax_rec_min (Node* Node);
    std::vector<Node*> createChild (Node* Node);
    void evaluateScore (Node* node);
    void shot (int character);
    nextOrientation (int character);
    void ApplyAction (Node* node);
  };

};

#endif
