// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H

#include "engine/CommandSet.h"
#include "state/State.h"

namespace ai {
  class EvolvedAI;
}

#include "EvolvedAI.h"

namespace ai {

  /// class HeuristicAI - Average AI. Choice the best action for the turn and don't anticipate much
  class HeuristicAI : public ai::EvolvedAI {
    // Attributes
  protected:
    engine::CommandSet* commands;
    // Operations
  public:
    HeuristicAI (state::State* state, int character);
    void choice ();
    void move (bool esquive);
    void nextOrientation ();
    void shot ();
    void run (engine::CommandSet& commands);
  };

};

#endif
