// Generated by dia2code
#ifndef AI__NODE__H
#define AI__NODE__H

#include <vector>
#include <stdlib.h>

namespace ai {
  class Node;
}

namespace ai {

  /// class Node - 
  class Node {
    // Attributes
  public:
    std::vector<Node*> children;
    int score;
    int depth;
    std::vector<int> choiceMove;
    // Operations
  public:
    int const getScore ();
    void setScore (int score);
    size_t const getChildCount ();
    Node* const getChild (size_t i);
  };

};

#endif
