// Generated by dia2code
#ifndef AI__SEARCHTREE__H
#define AI__SEARCHTREE__H

#include <vector>

namespace ai {
  class Node;
}

#include "Node.h"

namespace ai {

  /// class SearchTree - 
  class SearchTree {
    // Associations
    // Attributes
  public:
    Node* root;
    // Operations
  public:
    SearchTree ();
    void createTree (std::vector<Node*>& NodeWarehouse, Node* fromNode);
  };

};

#endif
