// Generated by dia2code
#ifndef AI__TREEAI__H
#define AI__TREEAI__H

#include "state/State.h"
#include "engine/CommandSet.h"

namespace ai {
  class Gardener;
  class EvolvedAI;
}

#include "EvolvedAI.h"
#include "Gardener.h"

namespace ai {

  /// class TreeAI - Best Ai. Use a tree for determining the best move to do
  class TreeAI : public ai::EvolvedAI {
    // Associations
    // Attributes
  protected:
    Gardener* slaveGardener;
    // Operations
  public:
    TreeAI (const state::State* state, int character);
    void run (engine::CommandSet& commands);
  };

};

#endif
