// Generated by dia2code
#ifndef STATE__DIRECTION__H
#define STATE__DIRECTION__H

namespace State {

  enum Direction {
    left down =1,
    left up = 2,
    rigth down = 3,
    right up = 4
  };

};

#endif
