// Generated by dia2code
#ifndef STATE__ELEMENTALLOC__H
#define STATE__ELEMENTALLOC__H

#include "State.h"

namespace State {

  /// class ElementAlloc - 
  template <  class E,   typename ID>
  class ElementAlloc : public State::AElementAlloc {
    // Attributes
  protected:
    ID id;
    // Operations
  public:
    ElementAlloc (ID id);
    Element* newInstance ();
  };

};

#endif
