// Generated by dia2code
#ifndef STATE__ELEMENTMOBILE__H
#define STATE__ELEMENTMOBILE__H

#include <string>

namespace state {
  class ElementBase;
  class ElementLiving;
}

#include "ElementLiving.h"

namespace state {

  /// class ElementMobile - 
  class ElementMobile : public state::ElementLiving {
    // Attributes
  private:
    /// Direction visé par l'objet
    int f_Direction;
    // Operations
  public:
    ElementMobile (int direction, int x, int y, int totalLife, int totalDefense, int id, bool canBeGetAcross = false, std::string name = NULL);
    int getDirection () const;
    void setDirection (int direction);
    ElementBase* clone () const;
    virtual void move (int dx, int dy);
  };

};

#endif
