// Generated by dia2code
#ifndef STATE__ELEMENTLIVING__H
#define STATE__ELEMENTLIVING__H

#include <string>

namespace state {
  class ElementBase;
}

#include "ElementBase.h"

namespace state {

  /// class ElementLiving - 
  class ElementLiving : public state::ElementBase {
    // Attributes
  protected:
    /// Vie de l'objet
    int f_Life;
    /// Defense de l'objet
    int f_Defense;
    // Operations
  public:
    ElementLiving (int life, int defense, int id, bool canBeGetAcross = false, std::string name = NULL);
    virtual ElementBase* clone () const;
    virtual int getLife () const;
    virtual int getDefense () const;
    virtual void takeDamage (int power, bool ignoreDefense);
  };

};

#endif
