// Generated by dia2code
#ifndef STATE__ELEMENTFACTORY__H
#define STATE__ELEMENTFACTORY__H

#include "state.h"

namespace state {

  /// class ElementFactory - 
  class ElementFactory {
    // Associations
    // Attributes
  protected:
    std map::<char ,AElementAlloc*> list;
    // Operations
  public:
    ~ElementFactory ();
    Element* const newInstance (char id);
    void registerType (char id, AElementAlloc* a);
  };

};

#endif
