// Generated by dia2code
#ifndef STATE__LISTEVEN__H
#define STATE__LISTEVEN__H

namespace State {

  /// class ListEven - 
  class ListEven {
    // Attributes
  public:
    const ElementList& list;
    int idx;
    // Operations
  public:
    ListEven (const ElementList& s, int idx);
    StateEven* const clone ();
  };

};

#endif
