// Generated by dia2code
#ifndef STATE__LISTEVEN__H
#define STATE__LISTEVEN__H

#include "state.h"

namespace state {

  /// class ListEven - 
  class ListEven : public state::StateEvent {
    // Attributes
  public:
    const ElementList& list;
    int idx;
    // Operations
  public:
    ListEven (const ElementList& s, int idx);
    StateEven* const clone ();
  };

};

#endif
