// Generated by dia2code
#ifndef STATE__MISSILE__H
#define STATE__MISSILE__H

#include "State.h"

namespace State {

  /// class Missile - 
  class Missile : public State::Projectile {
    // Attributes
  public:
    int Ceiling;
    int DistanceActuel;
    // Operations
  public:
    Missile ();
    Element const clone ();
    bool const equals (const Element& other);
    void setCeiling (int p);
    int const getCeiling ();
    void setDistance (int d);
    int getDistance ();
  };

};

#endif
