// Generated by dia2code
#ifndef STATE__MISSILE__H
#define STATE__MISSILE__H

#include "state.h"

namespace state {

  /// class Missile - 
  class Missile : public state::Projectile {
    // Attributes
  protected:
    int Ceiling;
    int DistanceActuel;
    // Operations
  public:
    Missile ();
    virtual Element* const clone ();
    virtual bool const equals (const Element& other);
    virtual bool const isMissile ();
    void setCeiling (int p);
    int const getCeiling ();
    void setDistance (int d);
    int getDistance ();
  };

};

#endif
