// Generated by dia2code
#ifndef STATE__MISSILE__H
#define STATE__MISSILE__H


namespace state {
  class Projectile;
}

#include "Projectile.h"

namespace state {

  /// class Missile - 
  class Missile : public state::Projectile {
    // Attributes
  protected:
    int Ceiling;
    int DistanceActuel;
    // Operations
  public:
    Missile ();
    virtual bool const isMissile ();
    void setCeiling (int p);
    int const getCeiling ();
    void setDistance (int d);
    int getDistance ();
    TypeId const getTypeId ();
  };

};

#endif
