// Generated by dia2code
#ifndef STATE__MISSILE__H
#define STATE__MISSILE__H


namespace state {
  class Projectile;
}

#include "TypeId.h"
#include "Projectile.h"

namespace state {

  /// class Missile - 
  class Missile : public state::Projectile {
    // Attributes
  protected:
    int Ceiling;
    int DistanceActuel;
    // Operations
  public:
    Missile ();
    virtual bool isMissile () const;
    void setCeiling (int p);
    int getCeiling () const;
    void setDistance (int d);
    int getDistance () const;
    TypeId getTypeId () const;
  };

};

#endif
