// Generated by dia2code
#ifndef STATE__MISSILE__H
#define STATE__MISSILE__H

#include "State.h"

namespace State {

  /// class Missile - 
  class Missile : public State::Mobile {
    // Associations
    State::MissileType MissileType;
    // Attributes
  protected:
    MissileType type;
    // Operations
  public:
    Missile ();
    Element const clone ();
    bool const equals (const Element& other);
    bool const isTank ();
    TypeId const getTypeId ();
    MissileType getMissileType ();
  };

};

#endif
