// Generated by dia2code
#ifndef STATE__MOBILEMANAGER__H
#define STATE__MOBILEMANAGER__H

#include <vector>
#include <string>

namespace state {
  class ElementMobile;
  class ElementBase;
}

#include "ElementMobile.h"

namespace state {

  /// class MobileManager - Manage the different element who can move
  class MobileManager {
    // Associations
    // Attributes
  private:
    std::vector<ElementMobile*> f_ElementList;
    // Operations
  public:
    MobileManager ();
    ~MobileManager ();
    ElementBase* getCell ( int posX, int posY) const;
    ElementBase* getElementByID (int id);
    ElementBase* getElementByName (std::string name);
    bool canMoveHere (int posX, int posY) const;
    void clear ();
    void load (std::string path);
  };

};

#endif
