// Generated by dia2code
#ifndef STATE__MOBILE__H
#define STATE__MOBILE__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class Mobile - 
  class Mobile : public state::Element {
    // Operations
  public:
    virtual bool const isStatic ();
    virtual bool const isTank () = 0;
  };

};

#endif
