// Generated by dia2code
#ifndef STATE__MOBILE__H
#define STATE__MOBILE__H

#include "state.h"

namespace state {

  /// class Mobile - 
  class Mobile : public state::Element {
    // Operations
  public:
    virtual bool const isStatic ();
    virtual bool const isTank () = 0;
  };

};

#endif
