// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include "state.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  protected:
    mutable std::vector<StateOberver*> observers;
    // Operations
  public:
    virtual ~Observable ();
    void const registerObserver (StateObserver* o);
    void const unregisterObserver (const StateEvent& e);
  };

};

#endif
