// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>

namespace state {
  class StateObserver;
  class StateEvent;
}

#include "StateObserver.h"

namespace state {

  /// class Observable - List of the class's observers 
  class Observable {
    // Associations
    // Attributes
  protected:
    mutable std::vector<StateObserver*> observers;
    // Operations
  public:
    ~Observable ();
    void registerObserver (StateObserver* obs) const;
    virtual void notifyObserver (const StateEvent& event) const;
  };

};

#endif
