// Generated by dia2code
#ifndef STATE__OBSTACLE__H
#define STATE__OBSTACLE__H

#include "State.h"

namespace State {

  /// class Obstacle - 
  class Obstacle : public State::StaticElement {
    // Associations
    State::ObstacleTypeId ObstacleType;
    // Attributes
  public:
     ;
    // Operations
  public:
    Obstacle (ObstacleTypeId id);
    bool const isSpace ();
    TypeId const getTypeId ();
    Element const clone ();
    bool const equals (const Element& other);
    void setObstacleTypeId (ObstacleTypeId id);
    ObstacleTypeId getObstacleTypeId ();
  };

};

#endif
