// Generated by dia2code
#ifndef STATE__OBSTACLETYPEID__H
#define STATE__OBSTACLETYPEID__H


namespace state {

  enum ObstacleTypeId {
    sand = 1,
    border     = 3,
    greenery = 2
  };

};

#endif
