// Generated by dia2code
#ifndef STATE__OBSTACLETYPEID__H
#define STATE__OBSTACLETYPEID__H

namespace State {

  enum ObstacleTypeId {
    sand = -,
    greenery = |,
    text = char
  };

};

#endif
