// Generated by dia2code
#ifndef STATE__OBSTACLE__H
#define STATE__OBSTACLE__H

#include "State.h"

namespace State {

  /// class Obstacle - 
  class Obstacle : public State::StaticElement {
    // Associations
    State::ObstacleTypeId ObstacleType;
    // Operations
  public:
    Obstacle (ObstacleTypeId id);
    virtual bool const isSpace ();
    TypeId const getTypeId ();
    virtual Element* const clone ();
    virtual bool const equals (const Element& other);
    void setObstacleTypeId (ObstacleTypeId id);
    ObstacleTypeId const getObstacleTypeId ();
  };

};

#endif
