// Generated by dia2code
#ifndef STATE__OBSTACLE__H
#define STATE__OBSTACLE__H


namespace state {
  class StaticElement;
}

#include "ObstacleTypeId.h"
#include "StaticElement.h"

namespace state {

  /// class Obstacle - 
  class Obstacle : public state::StaticElement {
    // Associations
    state::ObstacleTypeId ObstacleType;
    // Operations
  public:
    Obstacle (ObstacleTypeId id);
    virtual bool const isSpace ();
    TypeId const getTypeId ();
    void setObstacleTypeId (ObstacleTypeId id);
    ObstacleTypeId const getObstacleTypeId ();
  };

};

#endif
