// Generated by dia2code
#ifndef STATE__ORIENTATION__H
#define STATE__ORIENTATION__H


namespace state {

  enum Orientation {
    left_down =1,
    left_up = 2,
    rigth_down = 3,
    right_up = 4
  };

};

#endif
