// Generated by dia2code
#ifndef STATE__ORIENTATION__H
#define STATE__ORIENTATION__H

namespace State {

  enum Orientation {
    left down =1,
    left up = 2,
    rigth down = 3,
    right up = 4
  };

};

#endif
