// Generated by dia2code
#ifndef STATE__ORIENTATIONMISSILE__H
#define STATE__ORIENTATIONMISSILE__H

namespace state {

  enum OrientationMissile {
    left =1,
    rigth = 2,
    up = 3,
    down = 4
  };

};

#endif
