// Generated by dia2code
#ifndef STATE__PROJECTILEEVENT__H
#define STATE__PROJECTILEEVENT__H

#include "state/StateEvent.h"

namespace state {
  class StateEvent;
}

#include "StateEvent.h"

namespace state {

  /// class ProjectileEvent - 
  class ProjectileEvent : public state::StateEvent {
    // Attributes
  public:
    int xStart;
    int yStart;
    int xImpact;
    int yImpact;
    int yMax;
    bool rightDirection;
    // Operations
  public:
    ProjectileEvent (int xStart, int yStart, int xImpact, int yImpact, bool rightDirection = true, int yMax = -1);
    StateEvent* clone () const;
  };

};

#endif
