// Generated by dia2code
#ifndef STATE__PROJECTILE__H
#define STATE__PROJECTILE__H

#include "State.h"

namespace State {

  /// class Projectile - 
  class Projectile : public State::Mobile {
    // Associations
    State::OrientationMissile Orientation;
    // Operations
  public:
    bool const isTank ();
    virtual bool const isMissile () = 0;
    OrientationMissile const getOrientation ();
    void setOrientation (OrientationMissile o);
  };

};

#endif
