// Generated by dia2code
#ifndef STATE__SHELL__H
#define STATE__SHELL__H


namespace state {
  class Projectile;
}

#include "Projectile.h"

namespace state {

  /// class Shell - 
  class Shell : public state::Projectile {
    // Operations
  public:
    Shell ();
    virtual bool const isMissile ();
    TypeId const getTypeId ();
  };

};

#endif
