// Generated by dia2code
#ifndef STATE__SHELL__H
#define STATE__SHELL__H

#include "State.h"

namespace State {

  /// class Shell - 
  class Shell : public State::Projectile {
    // Operations
  public:
    Shell ();
    virtual Element* const clone ();
    virtual bool const equals (const Element& other);
    virtual bool const isMissile ();
  };

};

#endif
