// Generated by dia2code
#ifndef STATE__SHELL__H
#define STATE__SHELL__H

#include "state.h"

namespace state {

  /// class Shell - 
  class Shell : public state::Projectile {
    // Operations
  public:
    Shell ();
    virtual bool const isMissile ();
    TypeId const getTypeId ();
  };

};

#endif
