// Generated by dia2code
#ifndef STATE__SPACETYPEID__H
#define STATE__SPACETYPEID__H


namespace state {

  enum SpaceTypeId {
    startPlayer1 = 1,
    startPlayer2 = 2,
    empty = 3
  };

};

#endif
