// Generated by dia2code
#ifndef STATE__SPACE__H
#define STATE__SPACE__H

#include "State.h"

namespace State {

  /// class Space - 
  class Space : public State::StaticElement {
    // Associations
    State::SpaceTypeId SpaceTypeId;
    // Operations
  public:
    Space ();
    virtual bool const isSpace ();
    TypeId const getTypeId ();
    virtual Element* const clone ();
    virtual bool const equals (const Element& other);
    void setSpaceTypeId (SpaceTypeId id);
    SpaceTypeId const getSpaceTypeId ();
  };

};

#endif
