// Generated by dia2code
#ifndef STATE__SPACE__H
#define STATE__SPACE__H


namespace state {
  class StaticElement;
}

#include "TypeId.h"
#include "StaticElement.h"

namespace state {

  /// class Space - 
  class Space : public state::StaticElement {
    // Operations
  public:
    Space (int x, int y);
    virtual bool isSpace () const;
    TypeId getTypeId () const;
  };

};

#endif
