// Generated by dia2code
#ifndef STATE__STATICELEMENT__H
#define STATE__STATICELEMENT__H

#include "State.h"

namespace State {

  /// class StaticElement - 
  class StaticElement : public State::Element {
    // Operations
  public:
    bool const isStatic ();
    virtual bool const isSpace () = 0;
  };

};

#endif
