// Generated by dia2code
#ifndef STATE__STATEEVENT__H
#define STATE__STATEEVENT__H


namespace state {
  class State;
  class StateEvent;
  class StateObserver;
}

#include "StateEventId.h"
#include "StateObserver.h"

namespace state {

  /// class StateEvent - Event concerning the state
  class StateEvent {
    // Associations
    state::StateEventId id;
    // Attributes
  public:
    const State* s;
    // Operations
  public:
    StateEvent (const State* s, StateEventId id);
    virtual ~StateEvent ();
    bool operator== (StateEventId id) const;
    bool operator!= (StateEventId id) const;
    virtual StateEvent* clone () const;
  };

};

#endif
