// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class MobileManager;
  class WorldManager;
}

#include "MobileManager.h"
#include "WorldManager.h"

namespace state {

  /// class State - Store the list of the elements of the background (grid) and the list of the tank(mobiles)
  class State {
    // Associations
    // Attributes
  protected:
    /// Gestionnaire des éléments mobiles du jeu
    MobileManager mobiles;
    /// Gestionnaire des élèments fixes du jeu
    WorldManager grid;
    // Operations
  public:
    State ();
    ~State ();
    void load (const char* file_name);
  };

};

#endif
