// Generated by dia2code
#ifndef STATE__STATEOBSERVER__H
#define STATE__STATEOBSERVER__H

#include "state/StateEvent.h"

namespace state {
  class StateEvent;
}

namespace state {

  /// class StateObserver - API of the observers
  class StateObserver {
    // Operations
  public:
    virtual void stateChanged (const StateEvent& e) = 0;
  };

};

#endif
