// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include "state.h"

namespace state {

  /// class State - mobiles-> liste des truc mobile (tank, misile)
  class State {
    // Associations
    // Attributes
  protected:
    ElementList mobiles;
    ElementGrid grid;
    // Operations
  public:
    State ();
    ~State ();
    State* const clone ();
    bool const equals (const State& other);
    const ElementGrid& const getGrid ();
    const ElementList& const getMobiles ();
    const Mobile* const getMobile ( int idx);
    void setGrid (const ElementGrid& grid);
    void setMobiles (const ElementList& list);
    void loadLevel (const char* file_name);
    void setElementFactory (ElementFactory* factory);
  };

};

#endif
