// Generated by dia2code
#ifndef STATE__STATEEVENTID__H
#define STATE__STATEEVENTID__H


namespace state {

  enum StateEventId {
    Level_Changed     = 1,
    Element_Changed     = 2,
    Pv_Changed     = 3
  };

};

#endif
