// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include "state.h"

namespace state {

  /// class State - mobiles-> liste des truc mobile (tank, misile)
  class State {
    // Associations
    // Attributes
  protected:
    ElementList mobiles;
    ElementGrid grid;
    // Operations
  public:
    State ();
    ~State ();
    const ElementGrid& getGrid ();
    const ElementList&  getMobiles ();
    const Mobile* getMobile (int idx);
    void setGrid (const ElementGrid& grid);
    void setMobiles (const ElementList& list);
    void loadLevel (const char* file_name);
    void setElementFactory (ElementFactory* factory);
  };

};

#endif
