// Generated by dia2code
#ifndef __STATE__H
#define __STATE__H

# include  <memory>
# include <vector>



#include "State.h"
#include "ElementList.h"
#include "ElementGrid.h"


#include "StateEventId.h"
#include "StateEvent.h"
#include "StateObserver.h"
#include "Observable.h"







#include "TypeId.h"
#include "Element.h"
#include "AElementAlloc.h"
#include "ElementFactory.h"



#include "ObstacleTypeId.h"
#include "Orientation.h"
#include "PlayerType.h"
#include "TankTypeId.h"
#include "SpaceTypeId.h"
#include "ElementAlloc.h"
#include "OrientationMissile.h"
#include "ListEven.h"
#include "StaticElement.h"
#include "Obstacle.h"
#include "Space.h"
#include "Mobile.h"
#include "Projectile.h"
#include "Missile.h"
#include "Shell.h"
#include "Tank.h"
#endif
