// Generated by dia2code
#ifndef STATE__STATICELEMENT__H
#define STATE__STATICELEMENT__H

#include "state.h"

namespace state {

  /// class StaticElement - 
  class StaticElement : public state::Element {
    // Operations
  public:
    bool const isStatic ();
    virtual bool const isSpace () = 0;
  };

};

#endif
