// Generated by dia2code
#ifndef STATE__STATEOBSERVER__H
#define STATE__STATEOBSERVER__H

#include "State.h"

namespace State {

  /// class StateObserver - 
  class StateObserver {
    // Operations
  public:
    virtual void StateChanged (const StateEvent& e) = 0;
  };

};

#endif
