// Generated by dia2code
#ifndef STATE__TANKTYPEID__H
#define STATE__TANKTYPEID__H

namespace state {

  enum TankTypeId {
    Little tank  vert = 1,
    Little tank  grey = 2,
    Big tank vert = 3,
    Big tank grey = 4
  };

};

#endif
