// Generated by dia2code
#ifndef STATE__TANK__H
#define STATE__TANK__H

#include "state.h"

namespace state {

  /// class Tank - 
  class Tank : public state::Mobile {
    // Associations
    state::Orientation Orientation;
    state::PlayerType Player;
    state::TankTypeId TankType;
    // Attributes
  protected:
    int pv;
    // Operations
  public:
    Tank ();
    virtual bool const equals (const Element& other);
    virtual Element* const clone ();
    virtual bool const isTank ();
    TypeId const getTypeId ();
    bool const isPlayer ();
    void setPv (int pv);
    int const getPv ();
    state::Orientation const getOrientation ();
    void setOrientation (state::Orientation o);
    void setTankTypeId (TankTypeId id);
    TankTypeId getTankTypeId ();
  };

};

#endif
