// Generated by dia2code
#ifndef STATE__TANKTYPEID__H
#define STATE__TANKTYPEID__H

namespace state {

  enum TankTypeId {
    Little_tank_green = 1,
    Little_tank_grey = 2,
    Big_tank_green = 3,
    Big_tank_grey = 4
  };

};

#endif
