// Generated by dia2code
#ifndef STATE__TANK__H
#define STATE__TANK__H


namespace state {
  class Element;
}

#include "TankTypeId.h"
#include "Orientation.h"
#include "TypeId.h"
#include "Element.h"

namespace state {

  /// class Tank - 
  class Tank : public state::Element {
    // Associations
    state::TankTypeId TankType;
    state::Orientation orientation;
    // Operations
  public:
    Tank (TankTypeId tanktypeid, Orientation orientation, int x, int y);
    virtual bool isStatic () const;
    virtual bool isSolid () const;
    virtual TypeId getTypeId () const;
    Orientation getOrientation () const;
    void setOrientation (Orientation o);
    void setTankTypeId (TankTypeId id);
    TankTypeId getTankTypeId () const;
    Element* clone () const;
  };

};

#endif
