// Generated by dia2code
#ifndef STATE__TANK__H
#define STATE__TANK__H


namespace state {
  class Mobile;
}

#include "TypeId.h"
#include "Orientation.h"
#include "TankTypeId.h"
#include "Mobile.h"
#include "PlayerType.h"

namespace state {

  /// class Tank - 
  class Tank : public state::Mobile {
    // Associations
    state::TankTypeId TankType;
    state::PlayerType Player;
    state::Orientation orientation;
    // Attributes
  protected:
    int pv;
    // Operations
  public:
    Tank ();
    virtual bool isTank () const;
    virtual TypeId getTypeId () const;
    bool isPlayer () const;
    void setPv (int pv);
    int getPv () const;
    Orientation getOrientation () const;
    void setOrientation (Orientation o);
    void setTankTypeId (TankTypeId id);
    TankTypeId getTankTypeId () const;
  };

};

#endif
