// Generated by dia2code
#ifndef STATE__TEXT__H
#define STATE__TEXT__H

#include "State.h"

namespace State {

  /// class Text - 
  class Text : public State::StaticElement {
    // Attributes
  protected:
    char c;
    // Operations
  public:
    Text (char c);
    bool const isSpace ();
    TypeId const getTypeId ();
    Element const clone ();
    bool const equals (const Element& other);
    char const getChar ();
    void setChar (char newchar);
  };

};

#endif
