// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H

namespace State {

  enum TypeId {
    obstacle = 1,
    space = 2,
    tank = 3,
    missile = 4,
    shell = 5
  };

};

#endif
