// Generated by dia2code
#ifndef STATE__WORLDMANAGER__H
#define STATE__WORLDMANAGER__H

#include <vector>
#include <string>

namespace state {
  class ElementBase;
}

#include "ElementBase.h"

namespace state {

  /// class WorldManager - Manage the different element (stock the game world)
  class WorldManager {
    // Associations
    // Attributes
  private:
    int f_Width;
    int f_Height;
    std::vector<ElementBase*> f_ElementList;
    // Operations
  public:
    WorldManager (int width, int height);
    ~WorldManager ();
    ElementBase* getCell ( int posX, int posY) const;
    ElementBase* getElementByID (int id);
    ElementBase* getElementByName (std::string name);
    int getWidth () const;
    int getHeight () const;
    bool canMoveHere (int posX, int posY) const;
    void clear ();
    void load (std::string path);
  };

};

#endif
