// Generated by dia2code
#ifndef __CLIENT__H
#define __CLIENT__H

#include "client/Button.h"
#include "client/PiloteRendu.h"
#include "client/CacheStateObserver.h"
#include "client/PiloteSFML.h"
#include "client/Pilote.h"
#endif
