// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "render/Tile.h"
#include "render/Surface.h"
#include "render/Layer.h"
#include "render/Scene.h"
#include "render/LandscapeLayer.h"
#include "render/MobileLayer.h"
#include "render/CharLayer.h"
#endif
