// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H


#include "render/Surface.h"
#include "render/SurfaceSFML.h"
#include "render/Tile.h"
#include "render/Layer.h"
#include "render/Scene.h"
#endif
