// Generated by dia2code
#ifndef CLIENT__BUTTON__H
#define CLIENT__BUTTON__H

#include <vector>
#include <SFML/Graphics.hpp>
#include "engine/Engine.h"

namespace client {

  /// class Button - 
  class Button {
    // Attributes
  protected:
    std::vector<sf::Sprite*> s_button;
    sf::Texture m_tilesetButton;
    sf::IntRect* frame;
    engine::Command* command;
    // Operations
  public:
    Button (const char* image_file, engine::Command* command, unsigned int xTex, unsigned int widthButton, unsigned int heightButton, bool Hoover, unsigned int xPos, unsigned int yPos);
    void draw (sf::RenderWindow* window, sf::Vector2i localPosition) const;
    void press (sf::Vector2i localPosition, engine::Engine* engine) const;
  };

};

#endif
