// Generated by dia2code
#ifndef CLIENT__PILOTERENDU__H
#define CLIENT__PILOTERENDU__H


namespace client {

  /// class PiloteRendu - 
  class PiloteRendu {
    // Operations
  public:
    virtual void display () = 0;
  };

};

#endif
