// Generated by dia2code
#ifndef CLIENT__PILOTERENDU__H
#define CLIENT__PILOTERENDU__H


namespace client {

  /// class PiloteRendu - 
  class PiloteRendu {
    // Operations
  public:
    virtual void createMenu () = 0;
    virtual void display () = 0;
    virtual void eventUp () = 0;
    virtual void applyChange () = 0;
  };

};

#endif
