// Generated by dia2code
#ifndef CLIENT__PILOTERENDU__H
#define CLIENT__PILOTERENDU__H

#include "engine/Engine.h"

namespace client {

  /// class PiloteRendu - 
  class PiloteRendu {
    // Operations
  public:
    virtual void setEngine (engine::Engine* e) = 0;
    virtual void display () = 0;
  };

};

#endif
